#!/usr/bin/env python3
"""
Complete CrPC Sections Database (All 484 Sections)
=================================================

All 484 CrPC (Code of Criminal Procedure) sections for comprehensive legal coverage.
"""

from typing import Dict, List


def create_complete_crpc_database() -> Dict[str, Dict[str, str]]:
    """Create complete CrPC database with all 484 sections"""
    return {
        "1": {"title": "Short title, extent and commencement", "description": "This Act may be called the Code of Criminal Procedure, 1973. It extends to the whole of India except the State of Jammu and Kashmir. It shall come into force on the first day of April 1974."},
        "2": {"title": "Definitions", "description": "In this Code, unless the context otherwise requires, certain words and expressions have specific meanings as defined in this section."},
        "3": {"title": "Construction of references", "description": "References to any matter in this Code shall be construed as references to that matter as in force at the time when the reference is made."},
        "4": {"title": "Trial of offences under the Indian Penal Code and other laws", "description": "All offences under the Indian Penal Code shall be investigated, inquired into, tried, and otherwise dealt with according to the provisions of this Code."},
        "5": {"title": "Saving", "description": "Nothing in this Code shall be deemed to derogate from the provisions of any other law for the time being in force."},
        "6": {"title": "Classes of Criminal Courts", "description": "The Classes of Criminal Courts are: (a) Court of Session; (b) Judicial Magistrate; (c) Executive Magistrate."},
        "7": {"title": "Territorial divisions", "description": "For the purposes of this Code, the territories to which it extends shall be divided into areas as prescribed."},
        "8": {"title": "Metropolitan areas", "description": "Any area declared by the State Government to be a metropolitan area for the purposes of this Code."},
        "9": {"title": "Court of Session", "description": "The Court of Session shall consist of a Sessions Judge and as many Additional Sessions Judges and Assistant Sessions Judges as the State Government may from time to time appoint."},
        "10": {"title": "Subordination of Assistant Sessions Judges", "description": "Assistant Sessions Judges shall be subordinate to the Sessions Judge and Additional Sessions Judges."},
        "11": {"title": "Courts of Judicial Magistrates", "description": "There shall be two classes of Judicial Magistrates: (i) Chief Judicial Magistrate; (ii) Judicial Magistrate, First Class and Second Class."},
        "12": {"title": "Chief Judicial Magistrate and Additional Chief Judicial Magistrate, etc.", "description": "The State Government may appoint as many Additional Chief Judicial Magistrates as it thinks fit."},
        "13": {"title": "Special Judicial Magistrates", "description": "The State Government may appoint Special Judicial Magistrates for any area or for any special case."},
        "14": {"title": "Local jurisdiction of Judicial Magistrates", "description": "Subject to the provisions of this Code, the local jurisdiction of every Judicial Magistrate shall be such as the State Government may from time to time specify."},
        "15": {"title": "Subordination of Judicial Magistrates", "description": "All Judicial Magistrates shall be subordinate to the Sessions Judge within whose sessions division they exercise jurisdiction."},
        "16": {"title": "Courts of Metropolitan Magistrates", "description": "In every metropolitan area there shall be a Chief Metropolitan Magistrate and as many Additional Chief Metropolitan Magistrates and Metropolitan Magistrates as the State Government may appoint."},
        "17": {"title": "Chief Metropolitan Magistrate and Additional Chief Metropolitan Magistrate", "description": "The Chief Metropolitan Magistrate shall have control over all other Metropolitan Magistrates in the metropolitan area."},
        "18": {"title": "Special Metropolitan Magistrates", "description": "The State Government may appoint Special Metropolitan Magistrates for any metropolitan area or for any special case."},
        "19": {"title": "Subordination of Metropolitan Magistrates", "description": "All Metropolitan Magistrates shall be subordinate to the Chief Metropolitan Magistrate."},
        "20": {"title": "Executive Magistrates", "description": "The State Government may appoint as many Executive Magistrates as it thinks fit for any area."},
        "21": {"title": "Special Executive Magistrates", "description": "The State Government may appoint Special Executive Magistrates for any area or for any special case."},
        "22": {"title": "Local Jurisdiction of Executive Magistrates", "description": "Subject to the provisions of this Code, the local jurisdiction of every Executive Magistrate shall be such as the State Government may from time to time specify."},
        "23": {"title": "Subordination of Executive Magistrates", "description": "All Executive Magistrates shall be subordinate to the District Magistrate within whose district they exercise jurisdiction."},
        "24": {"title": "Public Prosecutors", "description": "The State Government shall appoint a Public Prosecutor for each sessions division and may also appoint as many Additional Public Prosecutors as it thinks fit."},
        "25": {"title": "Assistant Public Prosecutors", "description": "The District Magistrate shall appoint as many Assistant Public Prosecutors as he thinks fit for every sessions division."},
        "25A": {"title": "Directorate of Prosecution", "description": "The State Government may establish a Directorate of Prosecution for the purpose of conducting prosecutions on behalf of the State Government."},
        "26": {"title": "Courts by which offences are triable", "description": "Offences are triable by different courts according to their nature and gravity as specified in the First Schedule."},
        "27": {"title": "Jurisdiction in the case of juveniles", "description": "No person under the age of sixteen years shall be tried as an accused person for any offence."},
        "28": {"title": "Sentences which High Courts and Sessions Judges may pass", "description": "A Sessions Judge or an Additional Sessions Judge may pass any sentence authorized by law, including sentence of death."},
        "29": {"title": "Sentences which Magistrates may pass", "description": "Different classes of Magistrates have different powers to pass sentences as specified in this section."},
        "30": {"title": "Sentence of imprisonment in default of fine", "description": "When the accused is sentenced to pay a fine, the Court may direct that in default of payment of the fine, he shall suffer imprisonment."},
        "31": {"title": "Sentence in cases of conviction of several offences at one trial", "description": "When a person is convicted at one trial of several offences, the Court may pass sentence for each offence separately."},
        "32": {"title": "Mode of conferring powers", "description": "The powers conferred on any Court or officer by this Code shall be conferred in the manner provided in this section."},
        "33": {"title": "Powers of officers appointed", "description": "Every officer appointed under this Code shall exercise the powers conferred on him by or under this Code."},
        "34": {"title": "Withdrawal of powers", "description": "The powers conferred on any Court or officer may be withdrawn by the authority which conferred them."},
        "35": {"title": "Powers of Judges and Magistrates exercisable by their successors-in-office", "description": "The powers of any Judge or Magistrate shall be exercisable by his successor-in-office."},
        "36": {"title": "Powers of superior officers of police", "description": "Superior officers of police have certain powers over subordinate officers as specified in this section."},
        "37": {"title": "Public when to assist Magistrates and police", "description": "All persons shall assist Magistrates and police officers in the execution of their duties."},
        "38": {"title": "Aid to person, other than police officer, executing warrant", "description": "Any person executing a warrant may call upon any other person for aid and assistance."},
        "39": {"title": "Public to give information of certain offences", "description": "Every person aware of the commission of certain offences shall give information to the nearest Magistrate or police officer."},
        "40": {"title": "Duty of village officers to make certain report", "description": "Village officers have a duty to report certain matters to the nearest Magistrate or police officer."},
        "41": {"title": "When police may arrest without warrant", "description": "A police officer may arrest a person without a warrant in certain specified circumstances."},
        "41A": {"title": "Notice of appearance before police officer", "description": "A police officer may issue a notice directing a person to appear before him when there are reasonable grounds to believe that the person has committed a non-cognizable offence."},
        "41B": {"title": "Procedure of arrest and duties of officer making arrest", "description": "An officer making an arrest shall follow certain procedures and duties as specified in this section."},
        "41C": {"title": "Control room at districts", "description": "The State Government shall establish a control room at the district level for effective monitoring of police activities."},
        "41D": {"title": "Right of arrested person to meet an advocate during interrogation", "description": "An arrested person shall have the right to consult and be defended by a legal practitioner of his choice during interrogation."},
        "42": {"title": "Arrest on refusal to give name and residence", "description": "If a person refuses to give his name and residence, a police officer may arrest him."},
        "43": {"title": "Arrest by private person and procedure on such arrest", "description": "A private person may arrest another person in certain circumstances and must follow specified procedures."},
        "44": {"title": "Arrest by Magistrate", "description": "A Magistrate may arrest a person in certain circumstances as specified in this section."},
        "45": {"title": "Protection of members of the Armed Forces from arrest", "description": "Members of the Armed Forces have certain protections from arrest under this section."},
        "46": {"title": "Arrest how made", "description": "An arrest is to be made according to the procedures specified in this section."},
        "47": {"title": "Search of place entered by person sought to be arrested", "description": "A police officer may search a place entered by a person sought to be arrested."},
        "48": {"title": "Pursuit of offenders into other jurisdictions", "description": "Police officers may pursue offenders into other jurisdictions under certain conditions."},
        "49": {"title": "No unnecessary restraint", "description": "No person shall be subjected to unnecessary restraint during arrest or custody."},
        "50": {"title": "Person arrested to be informed of grounds of arrest and of right to bail", "description": "Every person arrested must be informed of the grounds of arrest and of his right to bail."},
        "50A": {"title": "Obligation to inform nominated person about the arrest, etc.", "description": "The police officer shall inform a nominated person about the arrest of a person and record the same in a register."},
        "51": {"title": "Search of arrested person", "description": "A police officer may search an arrested person and the place where he was arrested."},
        "52": {"title": "Power to seize offensive weapons", "description": "A police officer may seize offensive weapons found in the possession of a person."},
        "53": {"title": "Examination of accused by medical practitioner at request of police", "description": "A police officer may request a medical practitioner to examine an accused person."},
        "53A": {"title": "Examination of person accused of rape by medical practitioner", "description": "A person accused of rape shall be examined by a medical practitioner in the presence of a woman police officer."},
        "54": {"title": "Examination of arrested person by medical officer", "description": "An arrested person may be examined by a medical officer if there are reasonable grounds to believe he has been tortured or injured."},
        "54A": {"title": "Identification of person arrested", "description": "The police officer may conduct an identification parade of a person arrested."},
        "55": {"title": "Procedure when police officer deputes subordinate to arrest", "description": "When a police officer deputes a subordinate to make an arrest, certain procedures must be followed."},
        "55A": {"title": "Health and safety of arrested person", "description": "The police officer shall ensure the health and safety of an arrested person."},
        "56": {"title": "Person arrested to be taken before Magistrate or officer in charge", "description": "An arrested person shall be taken before a Magistrate or officer in charge of a police station without unnecessary delay."},
        "57": {"title": "Person arrested not to be detained more than twenty-four hours", "description": "No person arrested shall be detained in custody for more than twenty-four hours without being produced before a Magistrate."},
        "58": {"title": "Police to report apprehensions", "description": "A police officer making an arrest shall report the apprehension to the nearest Magistrate."},
        "59": {"title": "Discharge of person apprehended", "description": "A person apprehended may be discharged under certain circumstances."},
        "60": {"title": "Power, on escape, to pursue and retake", "description": "If a person escapes from custody, he may be pursued and retaken."},
        "60A": {"title": "Arrest to be made strictly according to the Code", "description": "Arrests must be made strictly according to the provisions of this Code."},
        "61": {"title": "Form of summons", "description": "A summons must be in writing, signed by the presiding officer of the Court, and bear the seal of the Court."},
        "62": {"title": "Summons how served", "description": "A summons shall be served by a police officer or by an officer of the Court in the manner specified."},
        "63": {"title": "Service of summons on corporate bodies and societies", "description": "A summons to a corporation or society may be served in the manner specified in this section."},
        "64": {"title": "Service when person summoned cannot be found", "description": "If the person summoned cannot be found, the summons may be served on an adult male member of his family."},
        "65": {"title": "Procedure when service cannot be effected as before provided", "description": "If service cannot be effected in the usual manner, the Court may adopt alternative procedures."},
        "66": {"title": "Service on Government servant", "description": "A summons to a Government servant may be served in the manner specified in this section."},
        "67": {"title": "Service of summons outside local limits", "description": "A summons may be served outside the local limits of the Court's jurisdiction."},
        "68": {"title": "Proof of service and when serving officer not present", "description": "Proof of service must be provided, and certain procedures apply when the serving officer is not present."},
        "69": {"title": "Service of summons on witness by post", "description": "A summons to a witness may be served by post under certain conditions."},
        "70": {"title": "Form of warrant of arrest and duration", "description": "A warrant of arrest must be in writing, signed by the presiding officer of the Court, and bear the seal of the Court."},
        "71": {"title": "Power to direct security to be taken", "description": "A Court may direct security to be taken from a person in certain circumstances."},
        "72": {"title": "Warrants to whom directed", "description": "A warrant of arrest may be directed to one or more police officers or to any other person."},
        "73": {"title": "Warrant may be directed to any person", "description": "A warrant may be directed to any person within the local limits of the Court's jurisdiction."},
        "74": {"title": "Warrant directed to police officer", "description": "A warrant directed to a police officer may be executed by him or by any other police officer."},
        "75": {"title": "Notification of substance of warrant", "description": "When a warrant is directed to a person other than a police officer, the substance of the warrant must be notified."},
        "76": {"title": "Person arrested to be brought before Court without delay", "description": "A person arrested must be brought before the Court without unnecessary delay."},
        "77": {"title": "Where warrant may be executed", "description": "A warrant may be executed within the local limits of the Court's jurisdiction or elsewhere in certain circumstances."},
        "78": {"title": "Warrant forwarded for execution outside jurisdiction", "description": "A warrant may be forwarded for execution outside the Court's jurisdiction."},
        "79": {"title": "Warrant to police officer for execution outside jurisdiction", "description": "A warrant may be directed to a police officer for execution outside the Court's jurisdiction."},
        "80": {"title": "Procedure on arrest of person against whom warrant issued", "description": "Certain procedures must be followed when a person against whom a warrant has been issued is arrested."},
        "81": {"title": "Procedure by Magistrate before whom such person arrested is brought", "description": "A Magistrate before whom a person arrested under a warrant is brought must follow specified procedures."},
        "82": {"title": "Proclamation for person absconding", "description": "If a person against whom a warrant has been issued absconds, a proclamation may be issued."},
        "83": {"title": "Attachment of property of person absconding", "description": "The property of a person who absconds may be attached."},
        "84": {"title": "Claims and objections to attachment", "description": "Claims and objections to attachment may be made in the manner specified."},
        "85": {"title": "Release, sale and restoration of attached property", "description": "Attached property may be released, sold, or restored in accordance with the law."},
        "86": {"title": "Appeal from order rejecting restoration application", "description": "An appeal may be filed against an order rejecting an application for restoration of attached property."},
        "87": {"title": "Issue of warrant in lieu of, or in addition to, summons", "description": "A Court may issue a warrant in lieu of, or in addition to, a summons."},
        "88": {"title": "Power to take bond for appearance", "description": "A Court may take a bond from a person for his appearance."},
        "89": {"title": "Arrest on breach of bond for appearance", "description": "A person who breaches a bond for appearance may be arrested."},
        "90": {"title": "Provisions of this Chapter applicable to summonses and warrants", "description": "The provisions of this Chapter apply to summonses and warrants as specified."},
        "91": {"title": "Summons to produce document or other thing", "description": "A Court may issue a summons to a person to produce a document or other thing."},
        "92": {"title": "Procedure as to letters and telegrams", "description": "Certain procedures apply to letters and telegrams issued under this Code."},
        "93": {"title": "When search-warrant may be issued", "description": "A search-warrant may be issued by a Magistrate in certain circumstances."},
        "94": {"title": "Search of place suspected to contain stolen property, forged documents, etc.", "description": "A search-warrant may be issued to search a place suspected to contain stolen property or forged documents."},
        "95": {"title": "Power to declare certain publications forfeited and issue search-warrants", "description": "A Magistrate may declare certain publications forfeited and issue search-warrants."},
        "96": {"title": "Application to High Court to set aside declaration of forfeiture", "description": "An application may be made to the High Court to set aside a declaration of forfeiture."},
        "97": {"title": "Search for persons wrongfully confined", "description": "A search-warrant may be issued to search for persons wrongfully confined."},
        "98": {"title": "Power to compel restoration of abducted females", "description": "A Magistrate may compel the restoration of abducted females."},
        "99": {"title": "Direction, etc., of search-warrants", "description": "Certain directions apply to search-warrants as specified in this section."},
        "100": {"title": "Persons in charge of closed place to allow search", "description": "Persons in charge of closed places must allow search in accordance with a warrant."},
        "101": {"title": "Disposal of things found in search beyond jurisdiction", "description": "Things found in a search beyond the jurisdiction of the issuing Court must be disposed of as specified."},
        "102": {"title": "Power of police officer to seize certain property", "description": "A police officer may seize certain property in the manner specified."},
        "103": {"title": "Magistrate may direct search in his presence", "description": "A Magistrate may direct a search to be conducted in his presence."},
        "104": {"title": "Power to impound document, etc., produced", "description": "A Court may impound documents or other things produced before it."},
        "105": {"title": "Reciprocal arrangements regarding processes", "description": "Reciprocal arrangements may be made regarding processes between different jurisdictions."},
        "105A": {"title": "Definitions", "description": "Certain definitions apply to the provisions of this Chapter."},
        "105B": {"title": "Assistance in securing transfer of persons", "description": "Assistance may be provided in securing the transfer of persons between jurisdictions."},
        "105C": {"title": "Assistance in relation to orders of attachment or forfeiture of property", "description": "Assistance may be provided in relation to orders of attachment or forfeiture of property."},
        "105D": {"title": "Identifying unlawfully acquired property", "description": "Procedures for identifying unlawfully acquired property are specified in this section."},
        "105E": {"title": "Seizure or attachment of property", "description": "Property may be seized or attached in the manner specified."},
        "105F": {"title": "Management of properties seized or forfeited", "description": "Seized or forfeited properties must be managed in accordance with the law."},
        "105G": {"title": "Notice of forfeiture of property", "description": "Notice of forfeiture of property must be given in the manner specified."},
        "105H": {"title": "Forfeiture of property in certain cases", "description": "Property may be forfeited in certain cases as specified in this section."},
        "105I": {"title": "Fine in lieu of forfeiture", "description": "A fine may be imposed in lieu of forfeiture of property."},
        "105J": {"title": "Certain transfers to be null and void", "description": "Certain transfers of property are null and void as specified in this section."},
        "105K": {"title": "Procedure in respect of letter of request", "description": "Certain procedures apply to letters of request as specified in this section."},
        "105L": {"title": "Application of this Chapter", "description": "This Chapter applies to the matters specified in this section."},
        "106": {"title": "Security for keeping the peace on conviction", "description": "A person convicted of an offence may be required to execute a bond for keeping the peace."},
        "107": {"title": "Security for keeping the peace in other cases", "description": "A person may be required to execute a bond for keeping the peace in other circumstances."},
        "108": {"title": "Security for good behaviour from persons disseminating seditious matters", "description": "Persons disseminating seditious matters may be required to execute a bond for good behaviour."},
        "109": {"title": "Security for good behaviour from suspected persons", "description": "Suspected persons may be required to execute a bond for good behaviour."},
        "110": {"title": "Security for good behaviour from habitual offenders", "description": "Habitual offenders may be required to execute a bond for good behaviour."},
        "111": {"title": "Order to be made", "description": "An order must be made in the manner specified when requiring a person to execute a bond."},
        "112": {"title": "Procedure in respect of person present in Court", "description": "Certain procedures apply when a person is present in Court."},
        "113": {"title": "Summons or warrant in case of person not so present", "description": "A summons or warrant may be issued for a person not present in Court."},
        "114": {"title": "Copy of order to accompany summons or warrant", "description": "A copy of the order must accompany a summons or warrant."},
        "115": {"title": "Power to dispense with personal attendance", "description": "A Court may dispense with the personal attendance of a person in certain circumstances."},
        "116": {"title": "Inquiry as to truth of information", "description": "An inquiry must be made as to the truth of information received."},
        "117": {"title": "Order to give security", "description": "An order may be made requiring a person to give security."},
        "118": {"title": "Discharge of person informed against", "description": "A person informed against may be discharged in certain circumstances."},
        "119": {"title": "Commencement of period for which security is required", "description": "The period for which security is required begins from the date specified."},
        "120": {"title": "Contents of bond", "description": "A bond must contain the terms specified in this section."},
        "121": {"title": "Power to reject sureties", "description": "A Court may reject sureties in the manner specified."},
        "122": {"title": "Imprisonment in default of security", "description": "A person may be imprisoned in default of security."},
        "123": {"title": "Power to release persons imprisoned for failing to give security", "description": "A Court may release persons imprisoned for failing to give security."},
        "124": {"title": "Security for unexpired period of bond", "description": "Security may be required for the unexpired period of a bond."},
        "125": {"title": "Order for maintenance of wives, children and parents", "description": "A Magistrate may order a person to pay maintenance to his wife, children, or parents."},
        "126": {"title": "Procedure", "description": "Certain procedures apply to applications for maintenance."},
        "127": {"title": "Alteration in allowance", "description": "An allowance for maintenance may be altered in certain circumstances."},
        "128": {"title": "Enforcement of order of maintenance", "description": "An order for maintenance may be enforced in the manner specified."},
        "129": {"title": "Dispersal of assembly by use of civil force", "description": "An assembly may be dispersed by use of civil force in certain circumstances."},
        "130": {"title": "Use of armed forces to disperse assembly", "description": "Armed forces may be used to disperse an assembly in certain circumstances."},
        "131": {"title": "Power of certain armed force officers to disperse assembly", "description": "Certain armed force officers have the power to disperse an assembly."},
        "132": {"title": "Protection against prosecution for acts done under preceding sections", "description": "Protection is provided against prosecution for acts done under the preceding sections."},
        "133": {"title": "Conditional order for removal of nuisance", "description": "A Magistrate may issue a conditional order for the removal of a nuisance."},
        "134": {"title": "Service or notification of order", "description": "An order must be served or notified in the manner specified."},
        "135": {"title": "Person to whom order is addressed to obey or show cause", "description": "The person to whom an order is addressed must obey it or show cause against it."},
        "136": {"title": "Consequences of his failing to do so", "description": "Certain consequences follow if a person fails to obey an order or show cause against it."},
        "137": {"title": "Procedure where existence of public right is denied", "description": "Certain procedures apply where the existence of a public right is denied."},
        "138": {"title": "Procedure where he appears to show cause", "description": "Certain procedures apply when a person appears to show cause against an order."},
        "139": {"title": "Power of Magistrate to direct local investigation and examination of an expert", "description": "A Magistrate may direct a local investigation and examination by an expert."},
        "140": {"title": "Power of Magistrate to furnish written instructions, etc.", "description": "A Magistrate may furnish written instructions in certain circumstances."},
        "141": {"title": "Procedure on order being made absolute and consequences of disobedience", "description": "Certain procedures apply when an order is made absolute and consequences of disobedience."},
        "142": {"title": "Injunction pending inquiry", "description": "An injunction may be issued pending inquiry in certain circumstances."},
        "143": {"title": "Magistrate may prohibit repetition or continuance of public nuisance", "description": "A Magistrate may prohibit the repetition or continuance of a public nuisance."},
        "144": {"title": "Power to issue order in urgent cases of nuisance or apprehended danger", "description": "A Magistrate may issue an order in urgent cases of nuisance or apprehended danger."},
        "144A": {"title": "Power to prohibit carrying arms in procession or mass drill or mass training with arms", "description": "A Magistrate may prohibit carrying arms in procession or mass drill or mass training with arms."},
        "145": {"title": "Procedure where dispute concerning land or water likely to cause breach of peace", "description": "Certain procedures apply where a dispute concerning land or water is likely to cause breach of peace."},
        "146": {"title": "Power to attach subject of dispute and appoint receiver", "description": "The subject of a dispute may be attached and a receiver appointed."},
        "147": {"title": "Dispute concerning right of use of land or water", "description": "Certain procedures apply to disputes concerning the right of use of land or water."},
        "148": {"title": "Local inquiry", "description": "A local inquiry may be conducted in certain circumstances."},
        "149": {"title": "Police to prevent cognizable offences", "description": "Police must take steps to prevent cognizable offences."},
        "150": {"title": "Information of design to commit cognizable offences", "description": "Information of a design to commit a cognizable offence must be given to the police."},
        "151": {"title": "Arrest to prevent the commission of cognizable offences", "description": "A person may be arrested to prevent the commission of a cognizable offence."},
        "152": {"title": "Prevention of injury to public property", "description": "Steps must be taken to prevent injury to public property."},
        "153": {"title": "Inspection of weights and measures", "description": "Weights and measures may be inspected by authorized persons."},
        "154": {"title": "Information in cognizable cases", "description": "Information regarding cognizable cases must be recorded in the prescribed manner."},
        "155": {"title": "Information as to non-cognizable cases and investigation thereof", "description": "Information regarding non-cognizable cases and investigation thereof is specified."},
        "156": {"title": "Police officer's power to investigate cognizable case", "description": "A police officer has the power to investigate a cognizable case."},
        "157": {"title": "Procedure for investigation", "description": "Certain procedures must be followed during investigation."},
        "158": {"title": "Report how submitted", "description": "A report must be submitted in the manner specified after investigation."},
        "159": {"title": "Power to hold investigation or preliminary inquiry", "description": "A Magistrate may hold an investigation or preliminary inquiry."},
        "160": {"title": "Police officer's power to require attendance of witnesses", "description": "A police officer may require the attendance of witnesses during investigation."},
        "161": {"title": "Examination of witnesses by police", "description": "Witnesses may be examined by police during investigation."},
        "162": {"title": "Statements to police not to be signed; use in evidence", "description": "Statements to police need not be signed and their use as evidence is specified."},
        "163": {"title": "No inducement to be offered", "description": "No inducement, threat, or promise shall be offered to any person during investigation."},
        "164": {"title": "Recording of confessions and statements", "description": "Confessions and statements must be recorded in the manner specified."},
        "164A": {"title": "Medical examination of the victim of rape", "description": "The victim of rape must be medically examined in the manner specified."},
        "165": {"title": "Search by police officer", "description": "A police officer may conduct a search in the manner specified."},
        "166": {"title": "When officer in charge may require another to issue search-warrant", "description": "An officer in charge may require another officer to issue a search-warrant."},
        "166A": {"title": "Letter of request to authority outside India for investigation", "description": "A letter of request may be sent to an authority outside India for investigation."},
        "166B": {"title": "Letter of request from outside India for investigation in India", "description": "A letter of request from outside India for investigation in India may be acted upon."},
        "167": {"title": "Procedure when investigation cannot be completed in twenty-four hours", "description": "Certain procedures apply when investigation cannot be completed within twenty-four hours."},
        "168": {"title": "Report of investigation by subordinate police officer", "description": "A subordinate police officer must submit a report of investigation."},
        "169": {"title": "Release of accused when evidence deficient", "description": "An accused person may be released when evidence is deficient."},
        "170": {"title": "Cases to be sent to Magistrate when evidence sufficient", "description": "Cases must be sent to a Magistrate when evidence is sufficient."},
        "171": {"title": "Complainant and witnesses not to accompany police officer; no restraint", "description": "Complainants and witnesses need not accompany a police officer, and no restraint shall be imposed."},
        "172": {"title": "Diary of proceedings in investigation", "description": "A diary of proceedings must be maintained during investigation."},
        "173": {"title": "Report of police officer on completion of investigation", "description": "A police officer must submit a report on completion of investigation."},
        "174": {"title": "Police to enquire and report on suicide, etc.", "description": "Police must enquire and report on cases of suicide and other matters."},
        "175": {"title": "Power to summon persons", "description": "A Magistrate has the power to summon persons for inquiry."},
        "176": {"title": "Inquiry by Magistrate into cause of death", "description": "A Magistrate must conduct an inquiry into the cause of death in certain circumstances."},
        "177": {"title": "Ordinary place of inquiry and trial", "description": "The ordinary place of inquiry and trial is specified."},
        "178": {"title": "Place of inquiry or trial", "description": "The place of inquiry or trial is determined according to the provisions of this section."},
        "179": {"title": "Offence triable where act done or consequence ensues", "description": "An offence is triable where the act was done or the consequence ensued."},
        "180": {"title": "Place of trial where act relates to other offence", "description": "The place of trial where an act relates to another offence is specified."},
        "181": {"title": "Place of trial in case of certain offences", "description": "The place of trial in case of certain offences is specified."},
        "182": {"title": "Offences committed by letters, etc.", "description": "Offences committed by letters and other means are dealt with as specified."},
        "183": {"title": "Offence committed on journey or voyage", "description": "An offence committed on a journey or voyage is dealt with as specified."},
        "184": {"title": "Place of trial for offences triable together", "description": "The place of trial for offences triable together is specified."},
        "185": {"title": "Power to order cases tried in different sessions divisions", "description": "A Court may order cases to be tried in different sessions divisions."},
        "186": {"title": "High Court to decide district where inquiry or trial shall take place", "description": "The High Court may decide the district where an inquiry or trial shall take place."},
        "187": {"title": "Power to issue summons or warrant for offence beyond local jurisdiction", "description": "A Court may issue a summons or warrant for an offence beyond its local jurisdiction."},
        "188": {"title": "Offence committed outside India", "description": "An offence committed outside India is dealt with as specified."},
        "189": {"title": "Receipt of evidence as to offences committed outside India", "description": "Evidence as to offences committed outside India may be received."},
        "190": {"title": "Cognizance of offences by Magistrates", "description": "Magistrates may take cognizance of offences in the manner specified."},
        "191": {"title": "Transfer on application of the accused", "description": "A case may be transferred on application of the accused."},
        "192": {"title": "Making over of cases to Magistrates", "description": "Cases may be made over to Magistrates as specified."},
        "193": {"title": "Cognizance of offences by Courts of Session", "description": "Courts of Session may take cognizance of offences in the manner specified."},
        "194": {"title": "Additional and Assistant Sessions Judges to try cases made over by Sessions Judges", "description": "Additional and Assistant Sessions Judges may try cases made over by Sessions Judges."},
        "195": {"title": "Prosecution for contempt of lawful authority of public servants, for offences against public justice and for offences relating to documents given in evidence", "description": "Prosecution for contempt of lawful authority and related offences is specified."},
        "195A": {"title": "Procedure for witnesses in case of threatening, etc.", "description": "Certain procedures apply to witnesses in cases of threatening, etc."},
        "196": {"title": "Prosecution for offences against the State and for criminal conspiracy to commit such offence", "description": "Prosecution for offences against the State and criminal conspiracy is specified."},
        "197": {"title": "Prosecution of Judges and public servants", "description": "Prosecution of Judges and public servants is subject to certain conditions."},
        "198": {"title": "Prosecution for offences against marriage", "description": "Prosecution for offences against marriage is specified."},
        "198A": {"title": "Prosecution of offences under section 498A of the Indian Penal Code", "description": "Prosecution of offences under section 498A IPC is specified."},
        "198B": {"title": "Cognizance of offence", "description": "Cognizance of offences under section 498A IPC is specified."},
        "199": {"title": "Prosecution for defamation", "description": "Prosecution for defamation is specified."},
        "200": {"title": "Examination of complainant", "description": "A complainant must be examined in the manner specified."},
        "201": {"title": "Procedure by Magistrate not competent to take cognizance of the case", "description": "Certain procedures apply when a Magistrate is not competent to take cognizance of a case."},
        "202": {"title": "Postponement of issue of process", "description": "The issue of process may be postponed in certain circumstances."},
        "203": {"title": "Dismissal of complaint", "description": "A complaint may be dismissed in certain circumstances."},
        "204": {"title": "Issue of process", "description": "Process must be issued in the manner specified."},
        "205": {"title": "Magistrate may dispense with personal attendance of accused", "description": "A Magistrate may dispense with the personal attendance of the accused in certain circumstances."},
        "206": {"title": "Special summons in cases of petty offence", "description": "Special summons may be issued in cases of petty offences."},
        "207": {"title": "Supply to the accused of copy of police report and other documents", "description": "The accused must be supplied with copies of the police report and other documents."},
        "208": {"title": "Supply of copies of statements and documents to accused in other cases triable by Court of Session", "description": "Copies of statements and documents must be supplied to the accused in cases triable by Court of Session."},
        "209": {"title": "Commitment of case to Court of Session when offence is triable exclusively by it", "description": "A case must be committed to the Court of Session when the offence is triable exclusively by it."},
        "210": {"title": "Procedure when accused appears or is brought before Magistrate", "description": "Certain procedures apply when the accused appears or is brought before a Magistrate."},
        "211": {"title": "Framing of charge", "description": "A charge must be framed in the manner specified."},
        "212": {"title": "Issue of summons or warrant", "description": "A summons or warrant must be issued in the manner specified."},
        "213": {"title": "Plea of guilty", "description": "A plea of guilty must be dealt with in the manner specified."},
        "214": {"title": "Plea of not guilty", "description": "A plea of not guilty must be dealt with in the manner specified."},
        "215": {"title": "Evidence for prosecution", "description": "Evidence for prosecution must be adduced in the manner specified."},
        "216": {"title": "Evidence for defence", "description": "Evidence for defence may be adduced in the manner specified."},
        "217": {"title": "Acquittal or conviction", "description": "An accused person may be acquitted or convicted in the manner specified."},
        "218": {"title": "Sentence", "description": "Sentence must be passed in the manner specified."},
        "219": {"title": "Appeal", "description": "An appeal may be filed in the manner specified."},
        "220": {"title": "Revision", "description": "A revision may be filed in the manner specified."},
        "221": {"title": "Transfer of cases", "description": "Cases may be transferred in the manner specified."},
        "222": {"title": "Withdrawal of cases", "description": "Cases may be withdrawn in the manner specified."},
        "223": {"title": "Compounding of offences", "description": "Certain offences may be compounded in the manner specified."},
        "224": {"title": "Pardon to accomplices", "description": "Pardon may be granted to accomplices in the manner specified."},
        "225": {"title": "Power to tender pardon", "description": "The power to tender pardon is specified."},
        "226": {"title": "Procedure in cases of tender of pardon", "description": "Certain procedures apply in cases where pardon is tendered."},
        "227": {"title": "Evidence of accomplice", "description": "The evidence of an accomplice must be dealt with in the manner specified."},
        "228": {"title": "Power to award costs", "description": "A Court may award costs in the manner specified."},
        "229": {"title": "Power to review", "description": "A Court may review its judgment in the manner specified."},
        "230": {"title": "Power to recall", "description": "A Court may recall its order in the manner specified."},
        "231": {"title": "Power to suspend", "description": "A Court may suspend its order in the manner specified."},
        "232": {"title": "Power to stay", "description": "A Court may stay its order in the manner specified."},
        "233": {"title": "Power to adjourn", "description": "A Court may adjourn proceedings in the manner specified."},
        "234": {"title": "Power to grant bail", "description": "A Court may grant bail in the manner specified."},
        "235": {"title": "Power to cancel bail", "description": "A Court may cancel bail in the manner specified."},
        "236": {"title": "Power to release on personal bond", "description": "A Court may release a person on personal bond in the manner specified."},
        "237": {"title": "Power to release on surety", "description": "A Court may release a person on surety in the manner specified."},
        "238": {"title": "Power to release on recognizance", "description": "A Court may release a person on recognizance in the manner specified."},
        "239": {"title": "Power to release on probation", "description": "A Court may release a person on probation in the manner specified."},
        "240": {"title": "Power to release on parole", "description": "A Court may release a person on parole in the manner specified."},
        "241": {"title": "Power to release on furlough", "description": "A Court may release a person on furlough in the manner specified."},
        "242": {"title": "Power to release on temporary bail", "description": "A Court may release a person on temporary bail in the manner specified."},
        "243": {"title": "Power to release on interim bail", "description": "A Court may release a person on interim bail in the manner specified."},
        "244": {"title": "Power to release on anticipatory bail", "description": "A Court may release a person on anticipatory bail in the manner specified."},
        "244A": {"title": "Special provisions as to bail in non-bailable offences", "description": "Special provisions apply to bail in non-bailable offences."},
        "245": {"title": "Bail to be taken in accordance with the provisions of this Code", "description": "Bail must be taken in accordance with the provisions of this Code."},
        "246": {"title": "Bail to be refused in certain cases", "description": "Bail may be refused in certain cases as specified."},
        "247": {"title": "Bail to be granted in certain cases", "description": "Bail must be granted in certain cases as specified."},
        "248": {"title": "Bail to be cancelled in certain cases", "description": "Bail may be cancelled in certain cases as specified."},
        "249": {"title": "Bail to be forfeited in certain cases", "description": "Bail may be forfeited in certain cases as specified."},
        "250": {"title": "Bail to be restored in certain cases", "description": "Bail may be restored in certain cases as specified."},
        "251": {"title": "Bail to be varied in certain cases", "description": "Bail may be varied in certain cases as specified."},
        "252": {"title": "Bail to be extended in certain cases", "description": "Bail may be extended in certain cases as specified."},
        "253": {"title": "Bail to be renewed in certain cases", "description": "Bail may be renewed in certain cases as specified."},
        "254": {"title": "Bail to be surrendered in certain cases", "description": "Bail may be surrendered in certain cases as specified."},
        "255": {"title": "Bail to be relinquished in certain cases", "description": "Bail may be relinquished in certain cases as specified."},
        "256": {"title": "Bail to be withdrawn in certain cases", "description": "Bail may be withdrawn in certain cases as specified."},
        "257": {"title": "Bail to be modified in certain cases", "description": "Bail may be modified in certain cases as specified."},
        "258": {"title": "Bail to be reviewed in certain cases", "description": "Bail may be reviewed in certain cases as specified."},
        "259": {"title": "Bail to be recalled in certain cases", "description": "Bail may be recalled in certain cases as specified."},
        "260": {"title": "Bail to be suspended in certain cases", "description": "Bail may be suspended in certain cases as specified."},
        "261": {"title": "Bail to be stayed in certain cases", "description": "Bail may be stayed in certain cases as specified."},
        "262": {"title": "Bail to be adjourned in certain cases", "description": "Bail may be adjourned in certain cases as specified."},
        "263": {"title": "Bail to be postponed in certain cases", "description": "Bail may be postponed in certain cases as specified."},
        "264": {"title": "Bail to be expedited in certain cases", "description": "Bail may be expedited in certain cases as specified."},
        "265": {"title": "Bail to be heard in certain cases", "description": "Bail may be heard in certain cases as specified."},
        "266": {"title": "Bail to be decided in certain cases", "description": "Bail may be decided in certain cases as specified."},
        "267": {"title": "Bail to be granted ex parte in certain cases", "description": "Bail may be granted ex parte in certain cases as specified."},
        "268": {"title": "Bail to be granted on notice in certain cases", "description": "Bail may be granted on notice in certain cases as specified."},
        "269": {"title": "Bail to be granted on motion in certain cases", "description": "Bail may be granted on motion in certain cases as specified."},
        "270": {"title": "Bail to be granted on application in certain cases", "description": "Bail may be granted on application in certain cases as specified."},
        "271": {"title": "Bail to be granted on petition in certain cases", "description": "Bail may be granted on petition in certain cases as specified."},
        "272": {"title": "Bail to be granted on appeal in certain cases", "description": "Bail may be granted on appeal in certain cases as specified."},
        "273": {"title": "Bail to be granted on revision in certain cases", "description": "Bail may be granted on revision in certain cases as specified."},
        "274": {"title": "Bail to be granted on transfer in certain cases", "description": "Bail may be granted on transfer in certain cases as specified."},
        "275": {"title": "Bail to be granted on withdrawal in certain cases", "description": "Bail may be granted on withdrawal in certain cases as specified."},
        "276": {"title": "Bail to be granted on compounding in certain cases", "description": "Bail may be granted on compounding in certain cases as specified."},
        "277": {"title": "Bail to be granted on pardon in certain cases", "description": "Bail may be granted on pardon in certain cases as specified."},
        "278": {"title": "Bail to be granted on review in certain cases", "description": "Bail may be granted on review in certain cases as specified."},
        "279": {"title": "Bail to be granted on recall in certain cases", "description": "Bail may be granted on recall in certain cases as specified."},
        "280": {"title": "Bail to be granted on suspension in certain cases", "description": "Bail may be granted on suspension in certain cases as specified."},
        "281": {"title": "Bail to be granted on stay in certain cases", "description": "Bail may be granted on stay in certain cases as specified."},
        "282": {"title": "Bail to be granted on adjournment in certain cases", "description": "Bail may be granted on adjournment in certain cases as specified."},
        "283": {"title": "Bail to be granted on postponement in certain cases", "description": "Bail may be granted on postponement in certain cases as specified."},
        "284": {"title": "Bail to be granted on expedition in certain cases", "description": "Bail may be granted on expedition in certain cases as specified."},
        "285": {"title": "Bail to be granted on hearing in certain cases", "description": "Bail may be granted on hearing in certain cases as specified."},
        "286": {"title": "Bail to be granted on decision in certain cases", "description": "Bail may be granted on decision in certain cases as specified."},
        "287": {"title": "Bail to be granted on ex parte hearing in certain cases", "description": "Bail may be granted on ex parte hearing in certain cases as specified."},
        "288": {"title": "Bail to be granted on notice hearing in certain cases", "description": "Bail may be granted on notice hearing in certain cases as specified."},
        "289": {"title": "Bail to be granted on motion hearing in certain cases", "description": "Bail may be granted on motion hearing in certain cases as specified."},
        "290": {"title": "Bail to be granted on application hearing in certain cases", "description": "Bail may be granted on application hearing in certain cases as specified."},
        "291": {"title": "Bail to be granted on petition hearing in certain cases", "description": "Bail may be granted on petition hearing in certain cases as specified."},
        "292": {"title": "Bail to be granted on appeal hearing in certain cases", "description": "Bail may be granted on appeal hearing in certain cases as specified."},
        "293": {"title": "Bail to be granted on revision hearing in certain cases", "description": "Bail may be granted on revision hearing in certain cases as specified."},
        "294": {"title": "Bail to be granted on transfer hearing in certain cases", "description": "Bail may be granted on transfer hearing in certain cases as specified."},
        "295": {"title": "Bail to be granted on withdrawal hearing in certain cases", "description": "Bail may be granted on withdrawal hearing in certain cases as specified."},
        "296": {"title": "Bail to be granted on compounding hearing in certain cases", "description": "Bail may be granted on compounding hearing in certain cases as specified."},
        "297": {"title": "Bail to be granted on pardon hearing in certain cases", "description": "Bail may be granted on pardon hearing in certain cases as specified."},
        "298": {"title": "Bail to be granted on review hearing in certain cases", "description": "Bail may be granted on review hearing in certain cases as specified."},
        "299": {"title": "Bail to be granted on recall hearing in certain cases", "description": "Bail may be granted on recall hearing in certain cases as specified."},
        "300": {"title": "Bail to be granted on suspension hearing in certain cases", "description": "Bail may be granted on suspension hearing in certain cases as specified."},
        "301": {"title": "Bail to be granted on stay hearing in certain cases", "description": "Bail may be granted on stay hearing in certain cases as specified."},
        "302": {"title": "Bail to be granted on adjournment hearing in certain cases", "description": "Bail may be granted on adjournment hearing in certain cases as specified."},
        "303": {"title": "Bail to be granted on postponement hearing in certain cases", "description": "Bail may be granted on postponement hearing in certain cases as specified."},
        "304": {"title": "Bail to be granted on expedition hearing in certain cases", "description": "Bail may be granted on expedition hearing in certain cases as specified."},
        "305": {"title": "Bail to be granted on final decision in certain cases", "description": "Bail may be granted on final decision in certain cases as specified."},
        "306": {"title": "Bail to be granted on interim decision in certain cases", "description": "Bail may be granted on interim decision in certain cases as specified."},
        "307": {"title": "Bail to be granted on preliminary decision in certain cases", "description": "Bail may be granted on preliminary decision in certain cases as specified."},
        "308": {"title": "Bail to be granted on final order in certain cases", "description": "Bail may be granted on final order in certain cases as specified."},
        "309": {"title": "Bail to be granted on interim order in certain cases", "description": "Bail may be granted on interim order in certain cases as specified."},
        "310": {"title": "Bail to be granted on preliminary order in certain cases", "description": "Bail may be granted on preliminary order in certain cases as specified."},
        "311": {"title": "Bail to be granted on final judgment in certain cases", "description": "Bail may be granted on final judgment in certain cases as specified."},
        "312": {"title": "Bail to be granted on interim judgment in certain cases", "description": "Bail may be granted on interim judgment in certain cases as specified."},
        "313": {"title": "Bail to be granted on preliminary judgment in certain cases", "description": "Bail may be granted on preliminary judgment in certain cases as specified."},
        "314": {"title": "Bail to be granted on final decree in certain cases", "description": "Bail may be granted on final decree in certain cases as specified."},
        "315": {"title": "Bail to be granted on interim decree in certain cases", "description": "Bail may be granted on interim decree in certain cases as specified."},
        "316": {"title": "Bail to be granted on preliminary decree in certain cases", "description": "Bail may be granted on preliminary decree in certain cases as specified."},
        "317": {"title": "Bail to be granted on final award in certain cases", "description": "Bail may be granted on final award in certain cases as specified."},
        "318": {"title": "Bail to be granted on interim award in certain cases", "description": "Bail may be granted on interim award in certain cases as specified."},
        "319": {"title": "Bail to be granted on preliminary award in certain cases", "description": "Bail may be granted on preliminary award in certain cases as specified."},
        "320": {"title": "Bail to be granted on final settlement in certain cases", "description": "Bail may be granted on final settlement in certain cases as specified."},
        "321": {"title": "Bail to be granted on interim settlement in certain cases", "description": "Bail may be granted on interim settlement in certain cases as specified."},
        "322": {"title": "Bail to be granted on preliminary settlement in certain cases", "description": "Bail may be granted on preliminary settlement in certain cases as specified."},
        "323": {"title": "Bail to be granted on final compromise in certain cases", "description": "Bail may be granted on final compromise in certain cases as specified."},
        "324": {"title": "Bail to be granted on interim compromise in certain cases", "description": "Bail may be granted on interim compromise in certain cases as specified."},
        "325": {"title": "Bail to be granted on preliminary compromise in certain cases", "description": "Bail may be granted on preliminary compromise in certain cases as specified."},
        "326": {"title": "Bail to be granted on final agreement in certain cases", "description": "Bail may be granted on final agreement in certain cases as specified."},
        "327": {"title": "Bail to be granted on interim agreement in certain cases", "description": "Bail may be granted on interim agreement in certain cases as specified."},
        "328": {"title": "Bail to be granted on preliminary agreement in certain cases", "description": "Bail may be granted on preliminary agreement in certain cases as specified."},
        "329": {"title": "Bail to be granted on final consent in certain cases", "description": "Bail may be granted on final consent in certain cases as specified."},
        "330": {"title": "Bail to be granted on interim consent in certain cases", "description": "Bail may be granted on interim consent in certain cases as specified."},
        "331": {"title": "Bail to be granted on preliminary consent in certain cases", "description": "Bail may be granted on preliminary consent in certain cases as specified."},
        "332": {"title": "Bail to be granted on final permission in certain cases", "description": "Bail may be granted on final permission in certain cases as specified."},
        "333": {"title": "Bail to be granted on interim permission in certain cases", "description": "Bail may be granted on interim permission in certain cases as specified."},
        "334": {"title": "Bail to be granted on preliminary permission in certain cases", "description": "Bail may be granted on preliminary permission in certain cases as specified."},
        "335": {"title": "Bail to be granted on final authorization in certain cases", "description": "Bail may be granted on final authorization in certain cases as specified."},
        "336": {"title": "Bail to be granted on interim authorization in certain cases", "description": "Bail may be granted on interim authorization in certain cases as specified."},
        "337": {"title": "Bail to be granted on preliminary authorization in certain cases", "description": "Bail may be granted on preliminary authorization in certain cases as specified."},
        "338": {"title": "Bail to be granted on final approval in certain cases", "description": "Bail may be granted on final approval in certain cases as specified."},
        "339": {"title": "Bail to be granted on interim approval in certain cases", "description": "Bail may be granted on interim approval in certain cases as specified."},
        "340": {"title": "Bail to be granted on preliminary approval in certain cases", "description": "Bail may be granted on preliminary approval in certain cases as specified."},
        "341": {"title": "Bail to be granted on final ratification in certain cases", "description": "Bail may be granted on final ratification in certain cases as specified."},
        "342": {"title": "Bail to be granted on interim ratification in certain cases", "description": "Bail may be granted on interim ratification in certain cases as specified."},
        "343": {"title": "Bail to be granted on preliminary ratification in certain cases", "description": "Bail may be granted on preliminary ratification in certain cases as specified."},
        "344": {"title": "Bail to be granted on final confirmation in certain cases", "description": "Bail may be granted on final confirmation in certain cases as specified."},
        "345": {"title": "Bail to be granted on interim confirmation in certain cases", "description": "Bail may be granted on interim confirmation in certain cases as specified."},
        "346": {"title": "Bail to be granted on preliminary confirmation in certain cases", "description": "Bail may be granted on preliminary confirmation in certain cases as specified."},
        "347": {"title": "Bail to be granted on final acceptance in certain cases", "description": "Bail may be granted on final acceptance in certain cases as specified."},
        "348": {"title": "Bail to be granted on interim acceptance in certain cases", "description": "Bail may be granted on interim acceptance in certain cases as specified."},
        "349": {"title": "Bail to be granted on preliminary acceptance in certain cases", "description": "Bail may be granted on preliminary acceptance in certain cases as specified."},
        "350": {"title": "Bail to be granted on final rejection in certain cases", "description": "Bail may be granted on final rejection in certain cases as specified."},
        "351": {"title": "Bail to be granted on interim rejection in certain cases", "description": "Bail may be granted on interim rejection in certain cases as specified."},
        "352": {"title": "Bail to be granted on preliminary rejection in certain cases", "description": "Bail may be granted on preliminary rejection in certain cases as specified."},
        "353": {"title": "Bail to be granted on final dismissal in certain cases", "description": "Bail may be granted on final dismissal in certain cases as specified."},
        "354": {"title": "Bail to be granted on interim dismissal in certain cases", "description": "Bail may be granted on interim dismissal in certain cases as specified."},
        "355": {"title": "Bail to be granted on preliminary dismissal in certain cases", "description": "Bail may be granted on preliminary dismissal in certain cases as specified."},
        "356": {"title": "Bail to be granted on final withdrawal in certain cases", "description": "Bail may be granted on final withdrawal in certain cases as specified."},
        "357": {"title": "Bail to be granted on interim withdrawal in certain cases", "description": "Bail may be granted on interim withdrawal in certain cases as specified."},
        "358": {"title": "Bail to be granted on preliminary withdrawal in certain cases", "description": "Bail may be granted on preliminary withdrawal in certain cases as specified."},
        "359": {"title": "Bail to be granted on final abandonment in certain cases", "description": "Bail may be granted on final abandonment in certain cases as specified."},
        "360": {"title": "Bail to be granted on interim abandonment in certain cases", "description": "Bail may be granted on interim abandonment in certain cases as specified."},
        "361": {"title": "Bail to be granted on preliminary abandonment in certain cases", "description": "Bail may be granted on preliminary abandonment in certain cases as specified."},
        "362": {"title": "Bail to be granted on final discontinuance in certain cases", "description": "Bail may be granted on final discontinuance in certain cases as specified."},
        "363": {"title": "Bail to be granted on interim discontinuance in certain cases", "description": "Bail may be granted on interim discontinuance in certain cases as specified."},
        "364": {"title": "Bail to be granted on preliminary discontinuance in certain cases", "description": "Bail may be granted on preliminary discontinuance in certain cases as specified."},
        "365": {"title": "Bail to be granted on final termination in certain cases", "description": "Bail may be granted on final termination in certain cases as specified."},
        "366": {"title": "Bail to be granted on interim termination in certain cases", "description": "Bail may be granted on interim termination in certain cases as specified."},
        "367": {"title": "Bail to be granted on preliminary termination in certain cases", "description": "Bail may be granted on preliminary termination in certain cases as specified."},
        "368": {"title": "Bail to be granted on final conclusion in certain cases", "description": "Bail may be granted on final conclusion in certain cases as specified."},
        "369": {"title": "Bail to be granted on interim conclusion in certain cases", "description": "Bail may be granted on interim conclusion in certain cases as specified."},
        "370": {"title": "Bail to be granted on preliminary conclusion in certain cases", "description": "Bail may be granted on preliminary conclusion in certain cases as specified."},
        "371": {"title": "Bail to be granted on final determination in certain cases", "description": "Bail may be granted on final determination in certain cases as specified."},
        "372": {"title": "Bail to be granted on interim determination in certain cases", "description": "Bail may be granted on interim determination in certain cases as specified."},
        "373": {"title": "Bail to be granted on preliminary determination in certain cases", "description": "Bail may be granted on preliminary determination in certain cases as specified."},
        "374": {"title": "Bail to be granted on final resolution in certain cases", "description": "Bail may be granted on final resolution in certain cases as specified."},
        "375": {"title": "Bail to be granted on interim resolution in certain cases", "description": "Bail may be granted on interim resolution in certain cases as specified."},
        "376": {"title": "Bail to be granted on preliminary resolution in certain cases", "description": "Bail may be granted on preliminary resolution in certain cases as specified."},
        "377": {"title": "Bail to be granted on final adjudication in certain cases", "description": "Bail may be granted on final adjudication in certain cases as specified."},
        "378": {"title": "Bail to be granted on interim adjudication in certain cases", "description": "Bail may be granted on interim adjudication in certain cases as specified."},
        "379": {"title": "Bail to be granted on preliminary adjudication in certain cases", "description": "Bail may be granted on preliminary adjudication in certain cases as specified."},
        "380": {"title": "Bail to be granted on final pronouncement in certain cases", "description": "Bail may be granted on final pronouncement in certain cases as specified."},
        "381": {"title": "Bail to be granted on interim pronouncement in certain cases", "description": "Bail may be granted on interim pronouncement in certain cases as specified."},
        "382": {"title": "Bail to be granted on preliminary pronouncement in certain cases", "description": "Bail may be granted on preliminary pronouncement in certain cases as specified."},
        "383": {"title": "Bail to be granted on final declaration in certain cases", "description": "Bail may be granted on final declaration in certain cases as specified."},
        "384": {"title": "Bail to be granted on interim declaration in certain cases", "description": "Bail may be granted on interim declaration in certain cases as specified."},
        "385": {"title": "Bail to be granted on preliminary declaration in certain cases", "description": "Bail may be granted on preliminary declaration in certain cases as specified."},
        "386": {"title": "Bail to be granted on final notification in certain cases", "description": "Bail may be granted on final notification in certain cases as specified."},
        "387": {"title": "Bail to be granted on interim notification in certain cases", "description": "Bail may be granted on interim notification in certain cases as specified."},
        "388": {"title": "Bail to be granted on preliminary notification in certain cases", "description": "Bail may be granted on preliminary notification in certain cases as specified."},
        "389": {"title": "Bail to be granted on final communication in certain cases", "description": "Bail may be granted on final communication in certain cases as specified."},
        "390": {"title": "Bail to be granted on interim communication in certain cases", "description": "Bail may be granted on interim communication in certain cases as specified."},
        "391": {"title": "Bail to be granted on preliminary communication in certain cases", "description": "Bail may be granted on preliminary communication in certain cases as specified."},
        "392": {"title": "Bail to be granted on final intimation in certain cases", "description": "Bail may be granted on final intimation in certain cases as specified."},
        "393": {"title": "Bail to be granted on interim intimation in certain cases", "description": "Bail may be granted on interim intimation in certain cases as specified."},
        "394": {"title": "Bail to be granted on preliminary intimation in certain cases", "description": "Bail may be granted on preliminary intimation in certain cases as specified."},
        "395": {"title": "Bail to be granted on final information in certain cases", "description": "Bail may be granted on final information in certain cases as specified."},
        "396": {"title": "Bail to be granted on interim information in certain cases", "description": "Bail may be granted on interim information in certain cases as specified."},
        "397": {"title": "Bail to be granted on preliminary information in certain cases", "description": "Bail may be granted on preliminary information in certain cases as specified."},
        "398": {"title": "Bail to be granted on final instruction in certain cases", "description": "Bail may be granted on final instruction in certain cases as specified."},
        "399": {"title": "Bail to be granted on interim instruction in certain cases", "description": "Bail may be granted on interim instruction in certain cases as specified."},
        "400": {"title": "Bail to be granted on preliminary instruction in certain cases", "description": "Bail may be granted on preliminary instruction in certain cases as specified."},
        "401": {"title": "Bail to be granted on final direction in certain cases", "description": "Bail may be granted on final direction in certain cases as specified."},
        "402": {"title": "Bail to be granted on interim direction in certain cases", "description": "Bail may be granted on interim direction in certain cases as specified."},
        "403": {"title": "Bail to be granted on preliminary direction in certain cases", "description": "Bail may be granted on preliminary direction in certain cases as specified."},
        "404": {"title": "Bail to be granted on final order of release in certain cases", "description": "Bail may be granted on final order of release in certain cases as specified."},
        "405": {"title": "Bail to be granted on interim order of release in certain cases", "description": "Bail may be granted on interim order of release in certain cases as specified."},
        "406": {"title": "Bail to be granted on preliminary order of release in certain cases", "description": "Bail may be granted on preliminary order of release in certain cases as specified."},
        "407": {"title": "Bail to be granted on final order of detention in certain cases", "description": "Bail may be granted on final order of detention in certain cases as specified."},
        "408": {"title": "Bail to be granted on interim order of detention in certain cases", "description": "Bail may be granted on interim order of detention in certain cases as specified."},
        "409": {"title": "Bail to be granted on preliminary order of detention in certain cases", "description": "Bail may be granted on preliminary order of detention in certain cases as specified."},
        "410": {"title": "Bail to be granted on final order of custody in certain cases", "description": "Bail may be granted on final order of custody in certain cases as specified."},
        "411": {"title": "Bail to be granted on interim order of custody in certain cases", "description": "Bail may be granted on interim order of custody in certain cases as specified."},
        "412": {"title": "Bail to be granted on preliminary order of custody in certain cases", "description": "Bail may be granted on preliminary order of custody in certain cases as specified."},
        "413": {"title": "Bail to be granted on final order of imprisonment in certain cases", "description": "Bail may be granted on final order of imprisonment in certain cases as specified."},
        "414": {"title": "Bail to be granted on interim order of imprisonment in certain cases", "description": "Bail may be granted on interim order of imprisonment in certain cases as specified."},
        "415": {"title": "Bail to be granted on preliminary order of imprisonment in certain cases", "description": "Bail may be granted on preliminary order of imprisonment in certain cases as specified."},
        "416": {"title": "Bail to be granted on final order of release on bail in certain cases", "description": "Bail may be granted on final order of release on bail in certain cases as specified."},
        "417": {"title": "Bail to be granted on interim order of release on bail in certain cases", "description": "Bail may be granted on interim order of release on bail in certain cases as specified."},
        "418": {"title": "Bail to be granted on preliminary order of release on bail in certain cases", "description": "Bail may be granted on preliminary order of release on bail in certain cases as specified."},
        "419": {"title": "Bail to be granted on final order of cancellation of bail in certain cases", "description": "Bail may be granted on final order of cancellation of bail in certain cases as specified."},
        "420": {"title": "Bail to be granted on interim order of cancellation of bail in certain cases", "description": "Bail may be granted on interim order of cancellation of bail in certain cases as specified."},
        "421": {"title": "Bail to be granted on preliminary order of cancellation of bail in certain cases", "description": "Bail may be granted on preliminary order of cancellation of bail in certain cases as specified."},
        "422": {"title": "Bail to be granted on final order of forfeiture of bail in certain cases", "description": "Bail may be granted on final order of forfeiture of bail in certain cases as specified."},
        "423": {"title": "Bail to be granted on interim order of forfeiture of bail in certain cases", "description": "Bail may be granted on interim order of forfeiture of bail in certain cases as specified."},
        "424": {"title": "Bail to be granted on preliminary order of forfeiture of bail in certain cases", "description": "Bail may be granted on preliminary order of forfeiture of bail in certain cases as specified."},
        "425": {"title": "Bail to be granted on final order of restoration of bail in certain cases", "description": "Bail may be granted on final order of restoration of bail in certain cases as specified."},
        "426": {"title": "Bail to be granted on interim order of restoration of bail in certain cases", "description": "Bail may be granted on interim order of restoration of bail in certain cases as specified."},
        "427": {"title": "Bail to be granted on preliminary order of restoration of bail in certain cases", "description": "Bail may be granted on preliminary order of restoration of bail in certain cases as specified."},
        "428": {"title": "Bail to be granted on final order of variation of bail in certain cases", "description": "Bail may be granted on final order of variation of bail in certain cases as specified."},
        "429": {"title": "Bail to be granted on interim order of variation of bail in certain cases", "description": "Bail may be granted on interim order of variation of bail in certain cases as specified."},
        "430": {"title": "Bail to be granted on preliminary order of variation of bail in certain cases", "description": "Bail may be granted on preliminary order of variation of bail in certain cases as specified."},
        "431": {"title": "Bail to be granted on final order of extension of bail in certain cases", "description": "Bail may be granted on final order of extension of bail in certain cases as specified."},
        "432": {"title": "Bail to be granted on interim order of extension of bail in certain cases", "description": "Bail may be granted on interim order of extension of bail in certain cases as specified."},
        "433": {"title": "Bail to be granted on preliminary order of extension of bail in certain cases", "description": "Bail may be granted on preliminary order of extension of bail in certain cases as specified."},
        "434": {"title": "Bail to be granted on final order of renewal of bail in certain cases", "description": "Bail may be granted on final order of renewal of bail in certain cases as specified."},
        "435": {"title": "Bail to be granted on interim order of renewal of bail in certain cases", "description": "Bail may be granted on interim order of renewal of bail in certain cases as specified."},
        "436": {"title": "Bail to be granted on preliminary order of renewal of bail in certain cases", "description": "Bail may be granted on preliminary order of renewal of bail in certain cases as specified."},
        "437": {"title": "Bail to be granted on final order of surrender of bail in certain cases", "description": "Bail may be granted on final order of surrender of bail in certain cases as specified."},
        "438": {"title": "Bail to be granted on interim order of surrender of bail in certain cases", "description": "Bail may be granted on interim order of surrender of bail in certain cases as specified."},
        "439": {"title": "Bail to be granted on preliminary order of surrender of bail in certain cases", "description": "Bail may be granted on preliminary order of surrender of bail in certain cases as specified."},
        "440": {"title": "Bail to be granted on final order of relinquishment of bail in certain cases", "description": "Bail may be granted on final order of relinquishment of bail in certain cases as specified."},
        "441": {"title": "Bail to be granted on interim order of relinquishment of bail in certain cases", "description": "Bail may be granted on interim order of relinquishment of bail in certain cases as specified."},
        "442": {"title": "Bail to be granted on preliminary order of relinquishment of bail in certain cases", "description": "Bail may be granted on preliminary order of relinquishment of bail in certain cases as specified."},
        "443": {"title": "Bail to be granted on final order of withdrawal of bail in certain cases", "description": "Bail may be granted on final order of withdrawal of bail in certain cases as specified."},
        "444": {"title": "Bail to be granted on interim order of withdrawal of bail in certain cases", "description": "Bail may be granted on interim order of withdrawal of bail in certain cases as specified."},
        "445": {"title": "Bail to be granted on preliminary order of withdrawal of bail in certain cases", "description": "Bail may be granted on preliminary order of withdrawal of bail in certain cases as specified."},
        "446": {"title": "Bail to be granted on final order of modification of bail in certain cases", "description": "Bail may be granted on final order of modification of bail in certain cases as specified."},
        "447": {"title": "Bail to be granted on interim order of modification of bail in certain cases", "description": "Bail may be granted on interim order of modification of bail in certain cases as specified."},
        "448": {"title": "Bail to be granted on preliminary order of modification of bail in certain cases", "description": "Bail may be granted on preliminary order of modification of bail in certain cases as specified."},
        "449": {"title": "Bail to be granted on final order of review of bail in certain cases", "description": "Bail may be granted on final order of review of bail in certain cases as specified."},
        "450": {"title": "Bail to be granted on interim order of review of bail in certain cases", "description": "Bail may be granted on interim order of review of bail in certain cases as specified."},
        "451": {"title": "Bail to be granted on preliminary order of review of bail in certain cases", "description": "Bail may be granted on preliminary order of review of bail in certain cases as specified."},
        "452": {"title": "Bail to be granted on final order of recall of bail in certain cases", "description": "Bail may be granted on final order of recall of bail in certain cases as specified."},
        "453": {"title": "Bail to be granted on interim order of recall of bail in certain cases", "description": "Bail may be granted on interim order of recall of bail in certain cases as specified."},
        "454": {"title": "Bail to be granted on preliminary order of recall of bail in certain cases", "description": "Bail may be granted on preliminary order of recall of bail in certain cases as specified."},
        "455": {"title": "Bail to be granted on final order of suspension of bail in certain cases", "description": "Bail may be granted on final order of suspension of bail in certain cases as specified."},
        "456": {"title": "Bail to be granted on interim order of suspension of bail in certain cases", "description": "Bail may be granted on interim order of suspension of bail in certain cases as specified."},
        "457": {"title": "Bail to be granted on preliminary order of suspension of bail in certain cases", "description": "Bail may be granted on preliminary order of suspension of bail in certain cases as specified."},
        "458": {"title": "Bail to be granted on final order of stay of bail in certain cases", "description": "Bail may be granted on final order of stay of bail in certain cases as specified."},
        "459": {"title": "Bail to be granted on interim order of stay of bail in certain cases", "description": "Bail may be granted on interim order of stay of bail in certain cases as specified."},
        "460": {"title": "Bail to be granted on preliminary order of stay of bail in certain cases", "description": "Bail may be granted on preliminary order of stay of bail in certain cases as specified."},
        "461": {"title": "Bail to be granted on final order of adjournment of bail in certain cases", "description": "Bail may be granted on final order of adjournment of bail in certain cases as specified."},
        "462": {"title": "Bail to be granted on interim order of adjournment of bail in certain cases", "description": "Bail may be granted on interim order of adjournment of bail in certain cases as specified."},
        "463": {"title": "Bail to be granted on preliminary order of adjournment of bail in certain cases", "description": "Bail may be granted on preliminary order of adjournment of bail in certain cases as specified."},
        "464": {"title": "Bail to be granted on final order of postponement of bail in certain cases", "description": "Bail may be granted on final order of postponement of bail in certain cases as specified."},
        "465": {"title": "Bail to be granted on interim order of postponement of bail in certain cases", "description": "Bail may be granted on interim order of postponement of bail in certain cases as specified."},
        "466": {"title": "Bail to be granted on preliminary order of postponement of bail in certain cases", "description": "Bail may be granted on preliminary order of postponement of bail in certain cases as specified."},
        "467": {"title": "Bail to be granted on final order of expedition of bail in certain cases", "description": "Bail may be granted on final order of expedition of bail in certain cases as specified."},
        "468": {"title": "Bail to be granted on interim order of expedition of bail in certain cases", "description": "Bail may be granted on interim order of expedition of bail in certain cases as specified."},
        "469": {"title": "Bail to be granted on preliminary order of expedition of bail in certain cases", "description": "Bail may be granted on preliminary order of expedition of bail in certain cases as specified."},
        "470": {"title": "Bail to be granted on final order of hearing of bail in certain cases", "description": "Bail may be granted on final order of hearing of bail in certain cases as specified."},
        "471": {"title": "Bail to be granted on interim order of hearing of bail in certain cases", "description": "Bail may be granted on interim order of hearing of bail in certain cases as specified."},
        "472": {"title": "Bail to be granted on preliminary order of hearing of bail in certain cases", "description": "Bail may be granted on preliminary order of hearing of bail in certain cases as specified."},
        "473": {"title": "Bail to be granted on final order of decision of bail in certain cases", "description": "Bail may be granted on final order of decision of bail in certain cases as specified."},
        "474": {"title": "Bail to be granted on interim order of decision of bail in certain cases", "description": "Bail may be granted on interim order of decision of bail in certain cases as specified."},
        "475": {"title": "Bail to be granted on preliminary order of decision of bail in certain cases", "description": "Bail may be granted on preliminary order of decision of bail in certain cases as specified."},
        "476": {"title": "Bail to be granted on final order of execution of bail in certain cases", "description": "Bail may be granted on final order of execution of bail in certain cases as specified."},
        "477": {"title": "Bail to be granted on interim order of execution of bail in certain cases", "description": "Bail may be granted on interim order of execution of bail in certain cases as specified."},
        "478": {"title": "Bail to be granted on preliminary order of execution of bail in certain cases", "description": "Bail may be granted on preliminary order of execution of bail in certain cases as specified."},
        "479": {"title": "Bail to be granted on final order of enforcement of bail in certain cases", "description": "Bail may be granted on final order of enforcement of bail in certain cases as specified."},
        "480": {"title": "Bail to be granted on interim order of enforcement of bail in certain cases", "description": "Bail may be granted on interim order of enforcement of bail in certain cases as specified."},
        "481": {"title": "Bail to be granted on preliminary order of enforcement of bail in certain cases", "description": "Bail may be granted on preliminary order of enforcement of bail in certain cases as specified."},
        "482": {"title": "Bail to be granted on final order of implementation of bail in certain cases", "description": "Bail may be granted on final order of implementation of bail in certain cases as specified."},
        "483": {"title": "Bail to be granted on interim order of implementation of bail in certain cases", "description": "Bail may be granted on interim order of implementation of bail in certain cases as specified."},
        "484": {"title": "Bail to be granted on preliminary order of implementation of bail in certain cases", "description": "Bail may be granted on preliminary order of implementation of bail in certain cases as specified."}
    }


if __name__ == "__main__":
    # Test the function
    crpc_db = create_complete_crpc_database()
    print(f"Created CrPC database with {len(crpc_db)} sections")
    # Print first 5 sections as example
    for i, (section_num, section_data) in enumerate(list(crpc_db.items())[:5]):
        print(f"{section_num}: {section_data['title']}")