#!/usr/bin/env python3
"""
Complete IPC Sections Database
==============================

All 511 IPC sections from the Indian Penal Code for comprehensive legal coverage.
"""

from typing import Dict, List


def create_complete_ipc_database() -> Dict[str, Dict[str, str]]:
    """Create complete IPC database with all 511 sections"""
    return {
        "1": {"title": "Title and extent of operation of the Code", "description": ""},
        "2": {"title": "Punishment of offences committed within India", "description": ""},
        "3": {"title": "Punishment of offences committed beyond but which by law may be tried within India", "description": ""},
        "4": {"title": "Extension of Code to extra-territorial offences", "description": ""},
        "5": {"title": "Certain laws not to be affected by this Act", "description": ""},
        "6": {"title": "Definitions in the Code to be understood subject to exceptions", "description": ""},
        "7": {"title": "Sense of expression once explained", "description": ""},
        "8": {"title": "Gender", "description": ""},
        "9": {"title": "Number", "description": ""},
        "10": {"title": "Man, Woman", "description": ""},
        "11": {"title": "Person", "description": ""},
        "12": {"title": "Public", "description": ""},
        "13": {"title": "Queen", "description": ""},
        "14": {"title": "Servant of Government", "description": ""},
        "15": {"title": "British India", "description": ""},
        "16": {"title": "Government of India", "description": ""},
        "17": {"title": "Government of a State", "description": ""},
        "18": {"title": "India", "description": ""},
        "19": {"title": "Judge", "description": ""},
        "20": {"title": "Court of Justice", "description": ""},
        "21": {"title": "Public servant", "description": ""},
        "22": {"title": "Movable property", "description": ""},
        "23": {"title": "Wrongful gain, Wrongful loss", "description": ""},
        "24": {"title": "Dishonestly", "description": ""},
        "25": {"title": "Fraudulently", "description": ""},
        "26": {"title": "Reason to believe", "description": ""},
        "27": {"title": "Property in possession of wife, clerk or servant", "description": ""},
        "28": {"title": "Counterfeit", "description": ""},
        "29": {"title": "Document", "description": ""},
        "29A": {"title": "Electronic record", "description": ""},
        "30": {"title": "Valuable security", "description": ""},
        "31": {"title": "A will", "description": ""},
        "32": {"title": "Words referring to acts include illegal omissions", "description": ""},
        "33": {"title": "Act, Omission", "description": ""},
        "34": {"title": "Acts done by several persons in furtherance of common intention", "description": ""},
        "35": {"title": "When such an act is criminal by reason of its being done with a criminal knowledge or intention", "description": ""},
        "36": {"title": "Effect caused partly by act and partly by omission", "description": ""},
        "37": {"title": "Co-operation by doing one of several acts constituting an offence", "description": ""},
        "38": {"title": "Persons concerned in criminal act may be guilty of different offences", "description": ""},
        "39": {"title": "\"Voluntarily\"", "description": ""},
        "40": {"title": "\"Offence\"", "description": ""},
        "41": {"title": "\"Special law\"", "description": ""},
        "42": {"title": "\"Local law\"", "description": ""},
        "43": {"title": "\"Illegal\", \"Legally bound to do\"", "description": ""},
        "44": {"title": "\"Injury\"", "description": ""},
        "45": {"title": "\"Life\"", "description": ""},
        "46": {"title": "\"Death\"", "description": ""},
        "47": {"title": "\"Animal\"", "description": ""},
        "48": {"title": "\"Vessel\"", "description": ""},
        "49": {"title": "\"Year\"; \"Month\"", "description": ""},
        "50": {"title": "\"Section\"", "description": ""},
        "51": {"title": "\"Oath\"", "description": ""},
        "52": {"title": "\"Good faith\"", "description": ""},
        "52A": {"title": "Harbour", "description": ""},
        "53": {"title": "Punishments", "description": ""},
        "53A": {"title": "Construction of reference to transportation", "description": ""},
        "54": {"title": "Commutation of sentence of death", "description": ""},
        "55": {"title": "Commutation of sentence of imprisonment for life", "description": ""},
        "55A": {"title": "Definition of \"appropriate Government\"", "description": ""},
        "56": {"title": "Sentence of Europeans and Americans to penal servitude", "description": ""},
        "57": {"title": "Fractions of terms of punishment", "description": ""},
        "58": {"title": "Offenders sentenced to transportation how dealt with until transported", "description": ""},
        "59": {"title": "Transportation instead of imprisonment", "description": ""},
        "60": {"title": "Sentence may be (in certain cases of imprisonment) wholly or partly rigorous or simple", "description": ""},
        "61": {"title": "Sentence of forfeiture of property", "description": ""},
        "62": {"title": "Forfeiture of property in respect of offenders punishable with death, transportation or imprisonment", "description": ""},
        "63": {"title": "Amount of fine", "description": ""},
        "64": {"title": "Sentence of imprisonment for non-payment of fine", "description": ""},
        "65": {"title": "Limit to imprisonment for non-payment of fine when the act punished with fine only", "description": ""},
        "66": {"title": "Description of imprisonment for non-payment of fine", "description": ""},
        "67": {"title": "Imprisonment for non-payment of fine, when offence punishable with fine only", "description": ""},
        "68": {"title": "Imprisonment to terminate on payment of fine", "description": ""},
        "69": {"title": "Termination of imprisonment on payment of proportional part of fine", "description": ""},
        "70": {"title": "Fine leviable within six years or during imprisonment—Death not to discharge property from liability", "description": ""},
        "71": {"title": "Limit of punishment of offence made up of several offences", "description": ""},
        "72": {"title": "Punishment of person guilty of one of several offences, judgment stating that it is doubtful of which", "description": ""},
        "73": {"title": "Solitary confinement", "description": ""},
        "74": {"title": "Limit of solitary confinement", "description": ""},
        "75": {"title": "Enhanced punishment for certain offences under Chapter XII or Chapter XVII after previous conviction", "description": ""},
        "76": {"title": "Act done by a person bound, or by mistake of fact believing himself bound, by law", "description": ""},
        "77": {"title": "Act of Judge when acting judicially", "description": ""},
        "78": {"title": "Act done pursuant to the judgment or order of Court", "description": ""},
        "79": {"title": "Act done by a person justified, or by mistake of fact believing himself justified, by law", "description": ""},
        "80": {"title": "Accident in doing a lawful act", "description": ""},
        "81": {"title": "Act likely to cause harm, but done without criminal intent, and to prevent other harm", "description": ""},
        "82": {"title": "Act of a child under seven years of age", "description": ""},
        "83": {"title": "Act of a child above seven and under twelve of immature understanding", "description": ""},
        "84": {"title": "Act of a person of unsound mind", "description": ""},
        "85": {"title": "Act of a person incapable of judgment by reason of intoxication caused against his will", "description": ""},
        "86": {"title": "Offence requiring a particular intent or knowledge committed by one who is intoxicated", "description": ""},
        "87": {"title": "Act not intended and not known to be likely to cause death or grievous hurt, done by consent", "description": ""},
        "88": {"title": "Act not intended to cause death, done by consent in good faith for person's benefit", "description": ""},
        "89": {"title": "Act done in good faith for benefit of child or insane person, by or by consent of guardian", "description": ""},
        "90": {"title": "Consent known to be given under fear or misconception", "description": ""},
        "91": {"title": "Exclusion of acts which are offences independently of harm caused", "description": ""},
        "92": {"title": "Act done in good faith for benefit of a person without consent", "description": ""},
        "93": {"title": "Communication made in good faith", "description": ""},
        "94": {"title": "Act to which a person is compelled by threats", "description": ""},
        "95": {"title": "Act causing slight harm", "description": ""},
        "96": {"title": "Things done in private defence", "description": ""},
        "97": {"title": "Right of private defence of the body and of property", "description": ""},
        "98": {"title": "Right of private defence against the act of a person of unsound mind, etc.", "description": ""},
        "99": {"title": "Acts against which there is no right of private defence", "description": ""},
        "100": {"title": "When the right of private defence of the body extends to causing death", "description": ""},
        "101": {"title": "When such right extends to causing any harm other than death", "description": ""},
        "102": {"title": "Commencement and continuance of the right of private defence of the body", "description": ""},
        "103": {"title": "When the right of private defence of property extends to causing death", "description": ""},
        "104": {"title": "When such right extends to causing any harm other than death", "description": ""},
        "105": {"title": "Commencement and continuance of the right of private defence of property", "description": ""},
        "106": {"title": "Right of private defence against deadly assault when there is risk of harm to innocent person", "description": ""},
        "107": {"title": "Abetment of a thing", "description": ""},
        "108": {"title": "Abettor", "description": ""},
        "108A": {"title": "Abetment in India of offences outside India", "description": ""},
        "109": {"title": "Punishment of abetment if the act abetted is committed in consequence and where no express provision is made for its punishment", "description": ""},
        "110": {"title": "Punishment of abetment if person abetted does act with different intention from that of abettor", "description": ""},
        "111": {"title": "Liability of abettor when one act abetted and different act done", "description": ""},
        "112": {"title": "Abettor when liable to cumulative punishment for act abetted and for act done", "description": ""},
        "113": {"title": "Liability of abettor for an effect caused by the act abetted different from that intended by the abettor", "description": ""},
        "114": {"title": "Abettor present when offence committed", "description": ""},
        "115": {"title": "Abetment of offence punishable with death or imprisonment for life—if offence not committed", "description": ""},
        "116": {"title": "Abetment of offence punishable with imprisonment—if offence be not committed", "description": ""},
        "117": {"title": "Abetting commission of offence by the public or by more than ten persons", "description": ""},
        "118": {"title": "Concealing design to commit offence punishable with death or imprisonment for life", "description": ""},
        "119": {"title": "Public servant concealing design to commit offence which it is his duty to prevent", "description": ""},
        "120": {"title": "Concealing design to commit offence punishable with imprisonment", "description": ""},
        "120A": {"title": "Definition of criminal conspiracy", "description": ""},
        "120B": {"title": "Punishment of criminal conspiracy", "description": ""},
        "121": {"title": "Waging, or attempting to wage war, or abetting waging of war, against the Government of India", "description": ""},
        "121A": {"title": "Conspiracy to commit offences punishable by Section 121", "description": ""},
        "122": {"title": "Collecting arms, etc., with intention of waging war against the Government of India", "description": ""},
        "123": {"title": "Concealing with intent to facilitate design to wage war", "description": ""},
        "124": {"title": "Assaulting President, Governor, etc., with intent to compel or restrain the exercise of any lawful power", "description": ""},
        "124A": {"title": "Sedition", "description": ""},
        "125": {"title": "Waging war against any Asiatic power in alliance with the Government of India", "description": ""},
        "126": {"title": "Committing depredation on territories of power at peace with the Government of India", "description": ""},
        "127": {"title": "Receiving property taken by war or depredation mentioned in Sections 125 and 126", "description": ""},
        "128": {"title": "Public servant voluntarily allowing prisoner of State or war to escape", "description": ""},
        "129": {"title": "Public servant negligently suffering such prisoner to escape", "description": ""},
        "130": {"title": "Aiding escape of, rescuing or harbouring such prisoner", "description": ""},
        "131": {"title": "Abetting mutiny, or attempting to seduce a soldier, sailor or airman from his duty", "description": ""},
        "132": {"title": "Abetment of mutiny, if mutiny is committed in consequence thereof", "description": ""},
        "133": {"title": "Abetment of assault by soldier, sailor or airman on his superior officer, when in execution of his office", "description": ""},
        "134": {"title": "Abetment of such assault, if the assault committed", "description": ""},
        "135": {"title": "Abetment of desertion of soldier, sailor or airman", "description": ""},
        "136": {"title": "Harbouring deserter", "description": ""},
        "137": {"title": "Deserter concealed on board merchant vessel through negligence of master", "description": ""},
        "138": {"title": "Abetment of act of insubordination by soldier, sailor or airman", "description": ""},
        "139": {"title": "Persons subject to certain Acts", "description": ""},
        "140": {"title": "Wearing garb or carrying token used by soldier, sailor or airman", "description": ""},
        "141": {"title": "Unlawful assembly", "description": ""},
        "142": {"title": "Being member of unlawful assembly", "description": ""},
        "143": {"title": "Punishment", "description": ""},
        "144": {"title": "Joining unlawful assembly armed with deadly weapon", "description": ""},
        "145": {"title": "Joining or continuing in unlawful assembly, knowing it has been commanded to disperse", "description": ""},
        "146": {"title": "Rioting", "description": ""},
        "147": {"title": "Punishment for rioting", "description": ""},
        "148": {"title": "Rioting, armed with deadly weapon", "description": ""},
        "149": {"title": "Every member of unlawful assembly guilty of offence committed in prosecution of common object", "description": ""},
        "150": {"title": "Hiring, or conniving at hiring, of persons to join unlawful assembly", "description": ""},
        "151": {"title": "Knowingly joining or continuing in assembly of five or more persons after it has been commanded to disperse", "description": ""},
        "152": {"title": "Assaulting or obstructing public servant when suppressing riot, etc.", "description": ""},
        "153": {"title": "Wantonly giving provocation with intent to cause riot—if rioting be committed; if not committed", "description": ""},
        "153A": {"title": "Promoting enmity between different groups on grounds of religion, race, place of birth, residence, language, etc., and doing acts prejudicial to maintenance of harmony", "description": ""},
        "153B": {"title": "Imputations, assertions prejudicial to national-integration", "description": ""},
        "154": {"title": "Owner or occupier of land on which an unlawful assembly is held", "description": ""},
        "155": {"title": "Liability of person for whose benefit riot is committed", "description": ""},
        "156": {"title": "Liability of agent of owner or occupier for whose benefit riot is committed", "description": ""},
        "157": {"title": "Harbouring persons hired for an unlawful assembly", "description": ""},
        "158": {"title": "Being hired to take part in an unlawful assembly or riot—promoting enmity between classes", "description": ""},
        "159": {"title": "Affray", "description": ""},
        "160": {"title": "Punishment for committing affray", "description": ""},
        "161": {"title": "Public servant taking gratification other than legal remuneration in respect of an official act", "description": ""},
        "162": {"title": "Taking gratification, in order, by corrupt or illegal means, to influence public servant", "description": ""},
        "163": {"title": "Taking gratification, for exercise of personal influence with public servant", "description": ""},
        "164": {"title": "Punishment for abetment by public servant of the offences defined in Section 162 or 163", "description": ""},
        "165": {"title": "Public servant obtaining valuable thing without consideration from person concerned in proceeding or business transacted by such public servant", "description": ""},
        "165A": {"title": "Punishment for abetment of offences defined in Section 161 or Section 165", "description": ""},
        "166": {"title": "Public servant disobeying law, with intent to cause injury to any person", "description": ""},
        "166A": {"title": "Public servant disobeying direction under law", "description": ""},
        "166B": {"title": "Punishment for non-treatment of victim", "description": ""},
        "167": {"title": "Public servant framing an incorrect document with intent to cause injury", "description": ""},
        "168": {"title": "Public servant unlawfully engaging in trade", "description": ""},
        "169": {"title": "Public servant unlawfully buying or bidding for property", "description": ""},
        "170": {"title": "Personating a public servant", "description": ""},
        "171": {"title": "Wearing garb or carrying token used by public servant with fraudulent intent", "description": ""},
        "171A": {"title": "\"Candidate\", \"Electoral right\" defined", "description": ""},
        "171B": {"title": "Bribery", "description": ""},
        "171C": {"title": "Undue influence at elections", "description": ""},
        "171D": {"title": "Personation at elections", "description": ""},
        "171E": {"title": "Punishment for bribery", "description": ""},
        "171F": {"title": "Punishment for undue influence or personation at an election", "description": ""},
        "171G": {"title": "False statement in connection with an election", "description": ""},
        "171H": {"title": "Illegal payments in connection with an election", "description": ""},
        "171I": {"title": "Failure to keep election accounts", "description": ""},
        "172": {"title": "Absconding to avoid service of summons or other proceeding", "description": ""},
        "173": {"title": "Preventing service of summons or other proceeding, or preventing publication thereof", "description": ""},
        "174": {"title": "Non-attendance in obedience to an order from public servant", "description": ""},
        "174A": {"title": "Non-appearance in response to a proclamation under Section 82 of the Code of Criminal Procedure, 1973", "description": ""},
        "175": {"title": "Omission to produce document or electronic record to public servant by person legally bound to produce it", "description": ""},
        "176": {"title": "Omission to give notice or information to public servant by person legally bound to give it", "description": ""},
        "177": {"title": "Furnishing false information", "description": ""},
        "178": {"title": "Refusing oath or affirmation when duly required by public servant to make it", "description": ""},
        "179": {"title": "Refusing to answer public servant authorised to question", "description": ""},
        "180": {"title": "Refusing to sign statement", "description": ""},
        "181": {"title": "False statement on oath or affirmation to public servant or person authorised to administer an oath or affirmation", "description": ""},
        "182": {"title": "False information, with intent to cause public servant to use his lawful power to the injury of another person", "description": ""},
        "183": {"title": "Resistance to the taking of property by the lawful authority of a public servant", "description": ""},
        "184": {"title": "Obstructing sale of property offered for sale by authority of public servant", "description": ""},
        "185": {"title": "Illegal purchase or bid for property offered for sale by authority of public servant", "description": ""},
        "186": {"title": "Obstructing public servant in discharge of public functions", "description": ""},
        "187": {"title": "Omission to assist public servant when bound by law to give assistance", "description": ""},
        "188": {"title": "Disobedience to order duly promulgated by public servant", "description": ""},
        "189": {"title": "Threat of injury to public servant", "description": ""},
        "190": {"title": "Threat of injury to induce person to refrain from applying for protection to public servant", "description": ""},
        "191": {"title": "Giving false evidence", "description": ""},
        "192": {"title": "Fabricating false evidence", "description": ""},
        "193": {"title": "Punishment for false evidence", "description": ""},
        "194": {"title": "Giving or fabricating false evidence with intent to procure conviction of capital offence", "description": ""},
        "195": {"title": "Giving or fabricating false evidence with intent to procure conviction of offence punishable with imprisonment for life or imprisonment", "description": ""},
        "195A": {"title": "Threatening any person to give false evidence", "description": ""},
        "196": {"title": "Using evidence known to be false", "description": ""},
        "197": {"title": "Issuing or signing false certificate", "description": ""},
        "198": {"title": "Using as true a certificate known to be false", "description": ""},
        "199": {"title": "False statement made in declaration which is by law receivable as evidence", "description": ""},
        "200": {"title": "Using as true such declaration knowing it to be false", "description": ""},
        "201": {"title": "Causing disappearance of evidence of offence, or giving false information to screen offender", "description": ""},
        "202": {"title": "Intentional omission to give information of offence by person bound to inform", "description": ""},
        "203": {"title": "Giving false information respecting an offence committed", "description": ""},
        "204": {"title": "Destruction of document or electronic record to prevent its production as evidence", "description": ""},
        "205": {"title": "False personation for purpose of act or proceeding in suit or prosecution", "description": ""},
        "206": {"title": "Fraudulent removal or concealment of property to prevent its seizure as forfeited or in execution", "description": ""},
        "207": {"title": "Fraudulent claim to property to prevent its seizure as forfeited or in execution", "description": ""},
        "208": {"title": "Fraudulently suffering decree for sum not due", "description": ""},
        "209": {"title": "Dishonestly making false claim in Court", "description": ""},
        "210": {"title": "Fraudulently obtaining decree for sum not due", "description": ""},
        "211": {"title": "False charge of offence made with intent to injure", "description": ""},
        "212": {"title": "Harbouring offender", "description": ""},
        "213": {"title": "Taking gift, etc., to screen an offender from punishment", "description": ""},
        "214": {"title": "Offering gift or restoration of property in consideration of screening offender", "description": ""},
        "215": {"title": "Taking gift to help to recover stolen property, etc.", "description": ""},
        "216": {"title": "Harbouring offender who has escaped from custody or whose apprehension has been ordered", "description": ""},
        "216A": {"title": "Penalty for harbouring robbers or dacoits", "description": ""},
        "216B": {"title": "Definition of \"harbour\" in sections 212, 216 and 216A", "description": ""},
        "217": {"title": "Public servant disobeying direction of law with intent to save person from punishment or property from forfeiture", "description": ""},
        "218": {"title": "Public servant framing incorrect record or writing with intent to save person from punishment or property from forfeiture", "description": ""},
        "219": {"title": "Public servant in judicial proceeding corruptly making report, etc., contrary to law", "description": ""},
        "220": {"title": "Commitment for trial or confinement by person having authority who knows that he is acting contrary to law", "description": ""},
        "221": {"title": "Intentional omission to apprehend on the part of public servant bound to apprehend", "description": ""},
        "222": {"title": "Intentional omission to apprehend on part of public servant bound to apprehend person under sentence or lawfully committed", "description": ""},
        "223": {"title": "Escape from confinement or custody negligently suffered by public servant", "description": ""},
        "224": {"title": "Resistance or obstruction by a person to his lawful apprehension", "description": ""},
        "225": {"title": "Resistance or obstruction to lawful apprehension of another person", "description": ""},
        "225A": {"title": "Omission to apprehend, or sufferance of escape, on part of public servant, in cases not otherwise provided for", "description": ""},
        "225B": {"title": "Resistance or obstruction to lawful apprehension or escape or rescue in cases not otherwise provided for", "description": ""},
        "226": {"title": "Unlawful return from transportation", "description": ""},
        "227": {"title": "Violation of condition of remission of punishment", "description": ""},
        "228": {"title": "Intentional insult or interruption to public servant sitting in judicial proceeding", "description": ""},
        "228A": {"title": "Disclosure of identity of the victim of certain offences", "description": ""},
        "229": {"title": "Personation of assessor", "description": ""},
        "229A": {"title": "Failure by person released on bail or bond to appear in Court", "description": ""},
        "230": {"title": "Coin defined", "description": ""},
        "231": {"title": "Counterfeiting coin", "description": ""},
        "232": {"title": "Counterfeiting coin", "description": ""},
        "233": {"title": "Making or possessing instruments or materials for counterfeiting coin", "description": ""},
        "234": {"title": "Making or selling instrument for counterfeiting coin", "description": ""},
        "235": {"title": "Possession of instrument, or material for the purpose of using the same for counterfeiting coin", "description": ""},
        "236": {"title": "Abetting in India the counterfeiting out of India of coin", "description": ""},
        "237": {"title": "Import or export of counterfeit coin", "description": ""},
        "238": {"title": "Import or export of counterfeits of the coin of a foreign country", "description": ""},
        "239": {"title": "Delivery of coin, as genuine, which, when first possessed, the deliverer did not know to be counterfeit", "description": ""},
        "240": {"title": "Delivery of coin, possessed with knowledge that it is counterfeit", "description": ""},
        "241": {"title": "Possession of counterfeit coin by person who knew it to be counterfeit when he became possessed thereof", "description": ""},
        "242": {"title": "Possession of counterfeit coin by person who knew it to be counterfeit when he became possessed thereof", "description": ""},
        "243": {"title": "Possession of counterfeit coin, with knowledge that it is counterfeit", "description": ""},
        "244": {"title": "Person employed in mint causing coin to be of different weight or composition from that fixed by law", "description": ""},
        "245": {"title": "Unlawfully taking coining instrument from mint", "description": ""},
        "246": {"title": "Fraudulently or dishonestly diminishing weight or altering composition of coin", "description": ""},
        "247": {"title": "Fraudulently or dishonestly diminishing weight or altering composition of coin", "description": ""},
        "248": {"title": "Altering appearance of coin with intent that it shall pass as coin of different description", "description": ""},
        "249": {"title": "Delivering coin as genuine, which, when first possessed, the deliverer did not know to be altered", "description": ""},
        "250": {"title": "Delivery of coin as genuine deemed counterfeit by reason of its being altered", "description": ""},
        "251": {"title": "Possession of coin by person who knew it to be altered when he became possessed thereof", "description": ""},
        "252": {"title": "Possession of coin by person who knew it to be altered when he became possessed thereof", "description": ""},
        "253": {"title": "Possession of coin by person who knew it to be altered when he became possessed thereof", "description": ""},
        "254": {"title": "Delivery of coin as genuine which is altered", "description": ""},
        "255": {"title": "Counterfeiting Government stamp", "description": ""},
        "256": {"title": "Having possession of instrument or material for counterfeiting Government stamp", "description": ""},
        "257": {"title": "Making or selling instrument for counterfeiting Government stamp", "description": ""},
        "258": {"title": "Sale of false weight or measure", "description": ""},
        "259": {"title": "Having possession of any instrument for the purpose of counterfeiting a Government stamp", "description": ""},
        "260": {"title": "Using as genuine a Government stamp known to be counterfeit", "description": ""},
        "261": {"title": "Effacing writing from substance bearing Government stamp, or removing from document a stamp used for it, with intent to cause loss to Government", "description": ""},
        "262": {"title": "Using Government stamp known to have been before used", "description": ""},
        "263": {"title": "Erasure of mark denoting that stamp has been used", "description": ""},
        "263A": {"title": "Prohibition of fictitious stamps", "description": ""},
        "264": {"title": "Fraudulent use of false instrument for weighing", "description": ""},
        "265": {"title": "Fraudulent use of false weight or measure", "description": ""},
        "266": {"title": "Being in possession of false weight or measure", "description": ""},
        "267": {"title": "Making or selling false weight or measure", "description": ""},
        "268": {"title": "Public nuisance", "description": ""},
        "269": {"title": "Negligent act likely to spread infection of disease dangerous to life", "description": ""},
        "270": {"title": "Malignant act likely to spread infection of disease dangerous to life", "description": ""},
        "271": {"title": "Disobedience to quarantine rule", "description": ""},
        "272": {"title": "Adulteration of food or drink intended for sale", "description": ""},
        "273": {"title": "Sale of noxious food or drink", "description": ""},
        "274": {"title": "Adulteration of drugs", "description": ""},
        "275": {"title": "Sale of adulterated drugs", "description": ""},
        "276": {"title": "Sale of drug as a different drug or preparation", "description": ""},
        "277": {"title": "Fouling water of public spring or reservoir", "description": ""},
        "278": {"title": "Making atmosphere noxious to health", "description": ""},
        "279": {"title": "Rash driving or riding on a public way", "description": ""},
        "280": {"title": "Rash navigation of vessel", "description": ""},
        "281": {"title": "Exhibition of false light, mark or buoy", "description": ""},
        "282": {"title": "Conveying person by water for hire in unsafe or overloaded vessel", "description": ""},
        "283": {"title": "Danger or obstruction in public way or line of navigation", "description": ""},
        "284": {"title": "Negligent conduct with respect to poisonous substance", "description": ""},
        "285": {"title": "Negligent conduct with respect to fire or combustible matter", "description": ""},
        "286": {"title": "Negligent conduct with respect to explosive substance", "description": ""},
        "287": {"title": "Negligent conduct with respect to machinery", "description": ""},
        "288": {"title": "Negligent conduct with respect to pulling down, repairing or constructing buildings, etc.", "description": ""},
        "289": {"title": "Negligent conduct with respect to animal", "description": ""},
        "290": {"title": "Punishment for public nuisance in cases not otherwise provided for", "description": ""},
        "291": {"title": "Continuance of nuisance after injunction to discontinue", "description": ""},
        "292": {"title": "Sale, etc., of obscene books, etc.", "description": ""},
        "293": {"title": "Sale, etc., of obscene objects to young person", "description": ""},
        "294": {"title": "Obscene acts and songs", "description": ""},
        "295": {"title": "Injuring or defiling place of worship with intent to insult the religion of any class", "description": ""},
        "295A": {"title": "Deliberate and malicious acts, intended to outrage religious feelings of any class by insulting its religion or religious beliefs", "description": ""},
        "296": {"title": "Disturbing religious assembly", "description": ""},
        "297": {"title": "Trespassing on burial places, etc.", "description": ""},
        "298": {"title": "Uttering words, etc., with deliberate intent to wound religious feelings", "description": ""},
        "299": {"title": "Culpable homicide", "description": ""},
        "300": {"title": "Murder", "description": ""},
        "301": {"title": "Culpable homicide by causing death of person other than person whose death was intended", "description": ""},
        "302": {"title": "Punishment for murder", "description": ""},
        "303": {"title": "Punishment for murder by life-convict", "description": ""},
        "304": {"title": "Punishment for culpable homicide not amounting to murder", "description": ""},
        "304A": {"title": "Causing death by negligence", "description": ""},
        "304B": {"title": "Dowry death", "description": ""},
        "305": {"title": "Abetment of suicide of child or insane person", "description": ""},
        "306": {"title": "Abetment of suicide", "description": ""},
        "307": {"title": "Attempt to murder", "description": ""},
        "308": {"title": "Attempt to commit culpable homicide", "description": ""},
        "309": {"title": "Attempt to commit suicide", "description": ""},
        "310": {"title": "Thug", "description": ""},
        "311": {"title": "Punishment", "description": ""},
        "312": {"title": "Causing miscarriage", "description": ""},
        "313": {"title": "Causing miscarriage without woman's consent", "description": ""},
        "314": {"title": "Death caused by act done with intent to cause miscarriage", "description": ""},
        "315": {"title": "Act done with intent to prevent child being born alive or to cause it to die after birth", "description": ""},
        "316": {"title": "Causing death of quick unborn child by act amounting to culpable homicide", "description": ""},
        "317": {"title": "Exposure and abandonment of child under twelve years", "description": ""},
        "318": {"title": "Concealment of birth by secret disposal of dead body", "description": ""},
        "319": {"title": "Hurt", "description": ""},
        "320": {"title": "Grievous hurt", "description": ""},
        "321": {"title": "Voluntarily causing hurt", "description": ""},
        "322": {"title": "Voluntarily causing grievous hurt", "description": ""},
        "323": {"title": "Punishment for voluntarily causing hurt", "description": ""},
        "324": {"title": "Voluntarily causing hurt by dangerous weapons or means", "description": ""},
        "325": {"title": "Punishment for voluntarily causing grievous hurt", "description": ""},
        "326": {"title": "Voluntarily causing grievous hurt by dangerous weapons or means", "description": ""},
        "326A": {"title": "Voluntarily causing grievous hurt by use of acid, etc.", "description": ""},
        "326B": {"title": "Voluntarily throwing or attempting to throw acid", "description": ""},
        "327": {"title": "Voluntarily causing hurt to extort property, or to constrain to an illegal act", "description": ""},
        "328": {"title": "Causing hurt by means of poison, etc., with intent to commit an offence", "description": ""},
        "329": {"title": "Voluntarily causing grievous hurt to extort property, or to constrain to an illegal act", "description": ""},
        "330": {"title": "Voluntarily causing hurt to extort confession, or to compel restoration of property", "description": ""},
        "331": {"title": "Voluntarily causing grievous hurt to extort confession, or to compel restoration of property", "description": ""},
        "332": {"title": "Voluntarily causing hurt to deter public servant from his duty", "description": ""},
        "333": {"title": "Voluntarily causing grievous hurt to deter public servant from his duty", "description": ""},
        "334": {"title": "Voluntarily causing hurt on provocation", "description": ""},
        "335": {"title": "Voluntarily causing grievous hurt on provocation", "description": ""},
        "336": {"title": "Act endangering life or personal safety of others", "description": ""},
        "337": {"title": "Causing hurt by act endangering life or personal safety of others", "description": ""},
        "338": {"title": "Causing grievous hurt by act endangering life or personal safety of others", "description": ""},
        "339": {"title": "Wrongful restraint", "description": ""},
        "340": {"title": "Wrongful confinement", "description": ""},
        "341": {"title": "Punishment for wrongful restraint", "description": ""},
        "342": {"title": "Punishment for wrongful confinement", "description": ""},
        "343": {"title": "Wrongful confinement for three or more days", "description": ""},
        "344": {"title": "Wrongful confinement for ten or more days", "description": ""},
        "345": {"title": "Wrongful confinement of person for whose liberation writ has been issued", "description": ""},
        "346": {"title": "Wrongful confinement in secret", "description": ""},
        "347": {"title": "Wrongful confinement to extort property, or constrain to illegal act", "description": ""},
        "348": {"title": "Wrongful confinement to extort confession, or compel restoration of property", "description": ""},
        "349": {"title": "Force", "description": ""},
        "350": {"title": "Criminal force", "description": ""},
        "351": {"title": "Assault", "description": ""},
        "352": {"title": "Punishment for assault or criminal force otherwise than on grave provocation", "description": ""},
        "353": {"title": "Assault or criminal force to deter public servant from discharge of his duty", "description": ""},
        "354": {"title": "Assault or criminal force to woman with intent to outrage her modesty", "description": ""},
        "354A": {"title": "Sexual harassment and punishment for sexual harassment", "description": ""},
        "354B": {"title": "Assault or use of criminal force to woman with intent to disrobe", "description": ""},
        "354C": {"title": "Voyeurism", "description": ""},
        "354D": {"title": "Stalking", "description": ""},
        "355": {"title": "Assault or criminal force with intent to dishonour person otherwise than on grave provocation", "description": ""},
        "356": {"title": "Assault or criminal force in attempt to commit theft of property carried by a person", "description": ""},
        "357": {"title": "Assault or criminal force in attempt to wrongfully confine a person", "description": ""},
        "358": {"title": "Assault or criminal force on grave provocation", "description": ""},
        "359": {"title": "Kidnapping", "description": ""},
        "360": {"title": "Kidnapping from India", "description": ""},
        "361": {"title": "Kidnapping from lawful guardianship", "description": ""},
        "362": {"title": "Abduction", "description": ""},
        "363": {"title": "Punishment for kidnapping", "description": ""},
        "363A": {"title": "Kidnapping or maiming a minor for purposes of begging", "description": ""},
        "364": {"title": "Kidnapping or abducting in order to murder", "description": ""},
        "364A": {"title": "Kidnapping for ransom, etc.", "description": ""},
        "365": {"title": "Kidnapping or abducting with intent secretly and wrongfully to confine person", "description": ""},
        "366": {"title": "Kidnapping, abducting or inducing woman to compel her marriage, etc.", "description": ""},
        "366A": {"title": "Procuration of minor girl", "description": ""},
        "366B": {"title": "Importation of girl from foreign country", "description": ""},
        "367": {"title": "Kidnapping or abducting in order to subject person to grievous hurt, slavery, etc.", "description": ""},
        "368": {"title": "Wrongfully concealing or keeping in confinement, kidnapped or abducted person", "description": ""},
        "369": {"title": "Kidnapping or abducting child under ten years with intent to steal from its person", "description": ""},
        "370": {"title": "Trafficking of person", "description": ""},
        "370A": {"title": "Exploitation of a trafficked person", "description": ""},
        "371": {"title": "Habitual dealing in slaves", "description": ""},
        "372": {"title": "Selling minor for purposes of prostitution", "description": ""},
        "373": {"title": "Buying minor for purposes of prostitution, etc.", "description": ""},
        "374": {"title": "Unlawful compulsory labour", "description": ""},
        "375": {"title": "Rape", "description": ""},
        "376": {"title": "Punishment for rape", "description": ""},
        "376A": {"title": "Punishment for causing death or resulting in persistent vegetative state of victim", "description": ""},
        "376AB": {"title": "Punishment for rape on woman under twelve years of age", "description": ""},
        "376B": {"title": "Sexual intercourse by husband upon his wife during separation", "description": ""},
        "376C": {"title": "Sexual intercourse by a person in authority", "description": ""},
        "376D": {"title": "Gang rape", "description": ""},
        "376DA": {"title": "Punishment for gang rape on woman under sixteen years of age", "description": ""},
        "376DB": {"title": "Punishment for gang rape on woman under twelve years of age", "description": ""},
        "376E": {"title": "Punishment for repeat offenders", "description": ""},
        "377": {"title": "Unnatural offences", "description": ""},
        "378": {"title": "Theft", "description": ""},
        "379": {"title": "Punishment for theft", "description": ""},
        "380": {"title": "Theft in dwelling house, etc.", "description": ""},
        "381": {"title": "Theft by clerk or servant of property in possession of master", "description": ""},
        "382": {"title": "Theft after preparation made for causing death, hurt or restraint in order to committing of the theft", "description": ""},
        "383": {"title": "Extortion", "description": ""},
        "384": {"title": "Punishment for extortion", "description": ""},
        "385": {"title": "Putting person in fear of injury in order to commit extortion", "description": ""},
        "386": {"title": "Extortion by putting a person in fear of death or grievous hurt", "description": ""},
        "387": {"title": "Putting person in fear of death or of grievous hurt, in order to commit extortion", "description": ""},
        "388": {"title": "Extortion by threat of accusation of an offence punishable with death or imprisonment for life, etc.", "description": ""},
        "389": {"title": "Putting person in fear of accusation of offence, in order to commit extortion", "description": ""},
        "390": {"title": "Robbery", "description": ""},
        "391": {"title": "Dacoity", "description": ""},
        "392": {"title": "Punishment for robbery", "description": ""},
        "393": {"title": "Attempt to commit robbery", "description": ""},
        "394": {"title": "Voluntarily causing hurt in committing robbery", "description": ""},
        "395": {"title": "Punishment for dacoity", "description": ""},
        "396": {"title": "Dacoity with murder", "description": ""},
        "397": {"title": "Robbery, or dacoity, with attempt to cause death or grievous hurt", "description": ""},
        "398": {"title": "Attempt to commit robbery or dacoity when armed with deadly weapon", "description": ""},
        "399": {"title": "Making preparation to commit dacoity", "description": ""},
        "400": {"title": "Punishment for belonging to gang of dacoits", "description": ""},
        "401": {"title": "Punishment for belonging to gang of thieves", "description": ""},
        "402": {"title": "Assembling for purpose of committing dacoity", "description": ""},
        "403": {"title": "Dishonest misappropriation of property", "description": ""},
        "404": {"title": "Dishonest misappropriation of property possessed by deceased person at the time of his death", "description": ""},
        "405": {"title": "Criminal breach of trust", "description": ""},
        "406": {"title": "Punishment for criminal breach of trust", "description": ""},
        "407": {"title": "Criminal breach of trust by carrier, etc.", "description": ""},
        "408": {"title": "Criminal breach of trust by clerk or servant", "description": ""},
        "409": {"title": "Criminal breach of trust by public servant, or by banker, merchant or agent", "description": ""},
        "410": {"title": "Stolen property", "description": ""},
        "411": {"title": "Dishonestly receiving stolen property", "description": ""},
        "412": {"title": "Dishonestly receiving property stolen in the commission of a dacoity", "description": ""},
        "413": {"title": "Habitually dealing in stolen property", "description": ""},
        "414": {"title": "Assisting in concealment of stolen property", "description": ""},
        "415": {"title": "Cheating", "description": ""},
        "416": {"title": "Cheating by personation", "description": ""},
        "417": {"title": "Punishment for cheating", "description": ""},
        "418": {"title": "Cheating with knowledge that wrongful loss may ensue to person whose interest offender is bound to protect", "description": ""},
        "419": {"title": "Punishment for cheating by personation", "description": ""},
        "420": {"title": "Cheating and dishonestly inducing delivery of property", "description": ""},
        "421": {"title": "Dishonest or fraudulent removal or concealment of property to prevent distribution among creditors", "description": ""},
        "422": {"title": "Dishonestly or fraudulently preventing debt being available for creditors", "description": ""},
        "423": {"title": "Dishonest or fraudulent execution of deed of transfer containing false statement of consideration", "description": ""},
        "424": {"title": "Dishonest or fraudulent removal or concealment of property", "description": ""},
        "425": {"title": "Mischief", "description": ""},
        "426": {"title": "Punishment for mischief", "description": ""},
        "427": {"title": "Mischief causing damage to the amount of fifty rupees", "description": ""},
        "428": {"title": "Mischief by killing or maiming animal of the value of ten rupees", "description": ""},
        "429": {"title": "Mischief by killing or maiming cattle, etc., of any value or any animal of the value of fifty rupees", "description": ""},
        "430": {"title": "Mischief by injury to works of irrigation or by wrongfully diverting water", "description": ""},
        "431": {"title": "Mischief by injury to public road, bridge, river or channel", "description": ""},
        "432": {"title": "Mischief by causing inundation or obstruction to public drainage", "description": ""},
        "433": {"title": "Mischief by destroying, moving or rendering less useful a light-house or sea-mark, etc.", "description": ""},
        "434": {"title": "Mischief by destroying or moving, etc., a land-mark fixed by public authority", "description": ""},
        "435": {"title": "Mischief by fire or explosive substance with intent to cause damage to amount of one hundred or (in case of agricultural produce) ten rupees", "description": ""},
        "436": {"title": "Mischief by fire or explosive substance with intent to destroy house, etc.", "description": ""},
        "437": {"title": "Mischief with intent to destroy or make unsafe a decked vessel or one of twenty tons burden", "description": ""},
        "438": {"title": "Punishment for the mischief described in Section 437 committed by fire or explosive substance", "description": ""},
        "439": {"title": "Punishment for intentionally running vessel aground or ashore with intent to commit theft, etc.", "description": ""},
        "440": {"title": "Mischief committed after preparation made for causing death or hurt", "description": ""},
        "441": {"title": "Criminal trespass", "description": ""},
        "442": {"title": "House-trespass", "description": ""},
        "443": {"title": "Lurking house-trespass", "description": ""},
        "444": {"title": "Lurking house-trespass by night", "description": ""},
        "445": {"title": "House-breaking", "description": ""},
        "446": {"title": "House-breaking by night", "description": ""},
        "447": {"title": "Punishment for criminal trespass", "description": ""},
        "448": {"title": "Punishment for house-trespass", "description": ""},
        "449": {"title": "House-trespass in order to commit offence punishable with death", "description": ""},
        "450": {"title": "House-trespass in order to commit offence punishable with imprisonment for life", "description": ""},
        "451": {"title": "House-trespass in order to commit offence punishable with imprisonment", "description": ""},
        "452": {"title": "House-trespass after preparation for hurt, assault or wrongful restraint", "description": ""},
        "453": {"title": "Lurking house-trespass or house-breaking", "description": ""},
        "454": {"title": "Lurking house-trespass or house-breaking in order to commit offence punishable with imprisonment", "description": ""},
        "455": {"title": "Lurking house-trespass or house-breaking after preparation for hurt, assault or wrongful restraint", "description": ""},
        "456": {"title": "Punishment for lurking house-trespass or house-breaking by night", "description": ""},
        "457": {"title": "Lurking house-trespass or house-breaking by night in order to commit offence punishable with imprisonment", "description": ""},
        "458": {"title": "Lurking house-trespass or house-breaking by night after preparation for hurt, assault or wrongful restraint", "description": ""},
        "459": {"title": "Grievous hurt caused while committing lurking house-trespass or house-breaking", "description": ""},
        "460": {"title": "All persons jointly concerned in lurking house-trespass or house-breaking punishable where death or grievous hurt caused by one of them", "description": ""},
        "461": {"title": "Dishonestly breaking open receptacle containing property", "description": ""},
        "462": {"title": "Punishment for same offence when committed by person entrusted with custody", "description": ""},
        "463": {"title": "Forgery", "description": ""},
        "464": {"title": "Making a false document", "description": ""},
        "465": {"title": "Punishment for forgery", "description": ""},
        "466": {"title": "Forgery of record of Court or of public register, etc.", "description": ""},
        "467": {"title": "Forgery of valuable security, will, etc.", "description": ""},
        "468": {"title": "Forgery for purpose of cheating", "description": ""},
        "469": {"title": "Forgery for purpose of harming reputation", "description": ""},
        "470": {"title": "Forged document or electronic record", "description": ""},
        "471": {"title": "Using as genuine a forged document or electronic record", "description": ""},
        "472": {"title": "Making or possessing counterfeit seal, etc., with intent to commit forgery punishable under Section 467", "description": ""},
        "473": {"title": "Making or possessing counterfeit seal, etc., with intent to commit forgery punishable otherwise", "description": ""},
        "474": {"title": "Having possession of document described in Section 466 or 467, knowing it to be forged and intending to use it as genuine", "description": ""},
        "475": {"title": "Counterfeiting device or mark used for authenticating documents described in Section 467, or possessing counterfeit marked material", "description": ""},
        "476": {"title": "Counterfeiting device or mark used for authenticating documents other than those described in Section 467, or possessing counterfeit marked material", "description": ""},
        "477": {"title": "Fraudulent cancellation, destruction, etc., of will, authority to adopt or valuable security", "description": ""},
        "477A": {"title": "Falsification of accounts", "description": ""},
        "478": {"title": "Trade, property marks", "description": ""},
        "479": {"title": "Property mark", "description": ""},
        "480": {"title": "Using a false trade mark", "description": ""},
        "481": {"title": "Using a false property mark", "description": ""},
        "482": {"title": "Punishment for using a false property mark", "description": ""},
        "483": {"title": "Counterfeiting a property mark used by another", "description": ""},
        "484": {"title": "Counterfeiting a property mark used by a public servant", "description": ""},
        "485": {"title": "Making or possession of any instrument for counterfeiting a property mark", "description": ""},
        "486": {"title": "Selling goods marked with a counterfeit property mark", "description": ""},
        "487": {"title": "Making a false mark upon any receptacle containing goods", "description": ""},
        "488": {"title": "Punishment for making use of any such false mark", "description": ""},
        "489": {"title": "Tampering with property mark with intent to cause injury", "description": ""},
        "489A": {"title": "Counterfeiting currency-notes or bank-notes", "description": ""},
        "489B": {"title": "Using as genuine, forged or counterfeit currency-notes or bank-notes", "description": ""},
        "489C": {"title": "Possession of forged or counterfeit currency-notes or bank-notes", "description": ""},
        "489D": {"title": "Making or possessing instruments or materials for forging or counterfeiting currency-notes or bank-notes", "description": ""},
        "489E": {"title": "Making or using documents resembling currency-notes or bank-notes", "description": ""},
        "490": {"title": "Breach of contract of service during voyage or journey", "description": ""},
        "491": {"title": "Breach of contract to attend on and supply wants of helpless person", "description": ""},
        "492": {"title": "Breach of contract to take care of and provide for child or other helpless person", "description": ""},
        "493": {"title": "Cohabitation caused by a man deceitfully inducing a belief of lawful marriage", "description": ""},
        "494": {"title": "Marrying again during lifetime of husband or wife", "description": ""},
        "495": {"title": "Same offence with concealment of former marriage from person with whom subsequent marriage is contracted", "description": ""},
        "496": {"title": "Marriage ceremony fraudulently gone through without lawful marriage", "description": ""},
        "497": {"title": "Adultery", "description": ""},
        "498": {"title": "Enticing or taking away or detaining with criminal intent a married woman", "description": ""},
        "498A": {"title": "Husband or relative of husband of a woman subjecting her to cruelty", "description": ""},
        "499": {"title": "Defamation", "description": ""},
        "500": {"title": "Punishment for defamation", "description": ""},
        "501": {"title": "Printing or engraving matter known to be defamatory", "description": ""},
        "502": {"title": "Sale of printed or engraved substance containing defamatory matter", "description": ""},
        "503": {"title": "Criminal intimidation", "description": ""},
        "504": {"title": "Intentional insult with intent to provoke breach of the peace", "description": ""},
        "505": {"title": "Statements conducing to public mischief", "description": ""},
        "506": {"title": "Punishment for criminal intimidation", "description": ""},
        "507": {"title": "Criminal intimidation by an anonymous communication", "description": ""},
        "508": {"title": "Act caused by inducing person to believe that he will be rendered an object of Divine displeasure", "description": ""},
        "509": {"title": "Word, gesture or act intended to insult the modesty of a woman", "description": ""},
        "510": {"title": "Misconduct in public by a drunken person", "description": ""},
        "511": {"title": "Punishment for attempting to commit offences", "description": ""}

    
    }
