#!/usr/bin/env python3
"""
Complete CrPC Sections Database
===============================

All CrPC (Code of Criminal Procedure) sections for comprehensive legal coverage.
"""

from typing import Dict, List


def create_complete_crpc_database() -> Dict[str, Dict[str, str]]:
    """Create complete CrPC database with all sections"""
    return {
        "1": {"title": "Short title, extent and commencement", "description": ""},
        "2": {"title": "Definitions", "description": ""},
        "3": {"title": "Construction of references", "description": ""},
        "4": {"title": "Trial of offences under the Indian Penal Code and other laws", "description": ""},
        "5": {"title": "Saving", "description": ""},
        "6": {"title": "Classes of Criminal Courts", "description": ""},
        "7": {"title": "Territorial divisions", "description": ""},
        "8": {"title": "Metropolitan areas", "description": ""},
        "9": {"title": "Court of Session", "description": ""},
        "10": {"title": "Subordination of Assistant Sessions Judges", "description": ""},
        "11": {"title": "Courts of Judicial Magistrates", "description": ""},
        "12": {"title": "Chief Judicial Magistrate and Additional Chief Judicial Magistrate, etc.", "description": ""},
        "13": {"title": "Special Judicial Magistrates", "description": ""},
        "14": {"title": "Local jurisdiction of Judicial Magistrates", "description": ""},
        "15": {"title": "Subordination of Judicial Magistrates", "description": ""},
        "16": {"title": "Courts of Metropolitan Magistrates", "description": ""},
        "17": {"title": "Chief Metropolitan Magistrate and Additional Chief Metropolitan Magistrate", "description": ""},
        "18": {"title": "Special Metropolitan Magistrates", "description": ""},
        "19": {"title": "Subordination of Metropolitan Magistrates", "description": ""},
        "20": {"title": "Executive Magistrates", "description": ""},
        "21": {"title": "Special Executive Magistrates", "description": ""},
        "22": {"title": "Local Jurisdiction of Executive Magistrates", "description": ""},
        "23": {"title": "Subordination of Executive Magistrates", "description": ""},
        "24": {"title": "Public Prosecutors", "description": ""},
        "25": {"title": "Assistant Public Prosecutors", "description": ""},
        "25A": {"title": "Directorate of Prosecution", "description": ""},
        "26": {"title": "Courts by which offences are triable", "description": ""},
        "27": {"title": "Jurisdiction in the case of juveniles", "description": ""},
        "28": {"title": "Sentences which High Courts and Sessions Judges may pass", "description": ""},
        "29": {"title": "Sentences which Magistrates may pass", "description": ""},
        "30": {"title": "Sentence of imprisonment in default of fine", "description": ""},
        "31": {"title": "Sentence in cases of conviction of several offences at one trial", "description": ""},
        "32": {"title": "Mode of conferring powers", "description": ""},
        "33": {"title": "Powers of officers appointed", "description": ""},
        "34": {"title": "Withdrawal of powers", "description": ""},
        "35": {"title": "Powers of Judges and Magistrates exercisable by their successors-in-office", "description": ""},
        "36": {"title": "Powers of superior officers of police", "description": ""},
        "37": {"title": "Public when to assist Magistrates and police", "description": ""},
        "38": {"title": "Aid to person, other than police officer, executing warrant", "description": ""},
        "39": {"title": "Public to give information of certain offences", "description": ""},
        "40": {"title": "Duty of village officers to make certain report", "description": ""},
        "41": {"title": "When police may arrest without warrant", "description": ""},
        "41A": {"title": "Notice of appearance before police officer", "description": ""},
        "41B": {"title": "Procedure of arrest and duties of officer making arrest", "description": ""},
        "41C": {"title": "Control room at districts", "description": ""},
        "41D": {"title": "Right of arrested person to meet an advocate during interrogation", "description": ""},
        "42": {"title": "Arrest on refusal to give name and residence", "description": ""},
        "43": {"title": "Arrest by private person and procedure on such arrest", "description": ""},
        "44": {"title": "Arrest by Magistrate", "description": ""},
        "45": {"title": "Protection of members of the Armed Forces from arrest", "description": ""},
        "46": {"title": "Arrest how made", "description": ""},
        "47": {"title": "Search of place entered by person sought to be arrested", "description": ""},
        "48": {"title": "Pursuit of offenders into other jurisdictions", "description": ""},
        "49": {"title": "No unnecessary restraint", "description": ""},
        "50": {"title": "Person arrested to be informed of grounds of arrest and of right to bail", "description": ""},
        "50A": {"title": "Obligation to inform nominated person about the arrest, etc.", "description": ""},
        "51": {"title": "Search of arrested person", "description": ""},
        "52": {"title": "Power to seize offensive weapons", "description": ""},
        "53": {"title": "Examination of accused by medical practitioner at request of police", "description": ""},
        "53A": {"title": "Examination of person accused of rape by medical practitioner", "description": ""},
        "54": {"title": "Examination of arrested person by medical officer", "description": ""},
        "54A": {"title": "Identification of person arrested", "description": ""},
        "55": {"title": "Procedure when police officer deputes subordinate to arrest", "description": ""},
        "55A": {"title": "Health and safety of arrested person", "description": ""},
        "56": {"title": "Person arrested to be taken before Magistrate or officer in charge", "description": ""},
        "57": {"title": "Person arrested not to be detained more than twenty-four hours", "description": ""},
        "58": {"title": "Police to report apprehensions", "description": ""},
        "59": {"title": "Discharge of person apprehended", "description": ""},
        "60": {"title": "Power, on escape, to pursue and retake", "description": ""},
        "60A": {"title": "Arrest to be made strictly according to the Code", "description": ""},
        "61": {"title": "Form of summons", "description": ""},
        "62": {"title": "Summons how served", "description": ""},
        "63": {"title": "Service of summons on corporate bodies and societies", "description": ""},
        "64": {"title": "Service when person summoned cannot be found", "description": ""},
        "65": {"title": "Procedure when service cannot be effected as before provided", "description": ""},
        "66": {"title": "Service on Government servant", "description": ""},
        "67": {"title": "Service of summons outside local limits", "description": ""},
        "68": {"title": "Proof of service and when serving officer not present", "description": ""},
        "69": {"title": "Service of summons on witness by post", "description": ""},
        "70": {"title": "Form of warrant of arrest and duration", "description": ""},
        "71": {"title": "Power to direct security to be taken", "description": ""},
        "72": {"title": "Warrants to whom directed", "description": ""},
        "73": {"title": "Warrant may be directed to any person", "description": ""},
        "74": {"title": "Warrant directed to police officer", "description": ""},
        "75": {"title": "Notification of substance of warrant", "description": ""},
        "76": {"title": "Person arrested to be brought before Court without delay", "description": ""},
        "77": {"title": "Where warrant may be executed", "description": ""},
        "78": {"title": "Warrant forwarded for execution outside jurisdiction", "description": ""},
        "79": {"title": "Warrant to police officer for execution outside jurisdiction", "description": ""},
        "80": {"title": "Procedure on arrest of person against whom warrant issued", "description": ""},
        "81": {"title": "Procedure by Magistrate before whom such person arrested is brought", "description": ""},
        "82": {"title": "Proclamation for person absconding", "description": ""},
        "83": {"title": "Attachment of property of person absconding", "description": ""},
        "84": {"title": "Claims and objections to attachment", "description": ""},
        "85": {"title": "Release, sale and restoration of attached property", "description": ""},
        "86": {"title": "Appeal from order rejecting restoration application", "description": ""},
        "87": {"title": "Issue of warrant in lieu of, or in addition to, summons", "description": ""},
        "88": {"title": "Power to take bond for appearance", "description": ""},
        "89": {"title": "Arrest on breach of bond for appearance", "description": ""},
        "90": {"title": "Provisions of this Chapter applicable to summonses and warrants", "description": ""},
        "91": {"title": "Summons to produce document or other thing", "description": ""},
        "92": {"title": "Procedure as to letters and telegrams", "description": ""},
        "93": {"title": "When search-warrant may be issued", "description": ""},
        "94": {"title": "Search of place suspected to contain stolen property, forged documents, etc.", "description": ""},
        "95": {"title": "Power to declare certain publications forfeited and issue search-warrants", "description": ""},
        "96": {"title": "Application to High Court to set aside declaration of forfeiture", "description": ""},
        "97": {"title": "Search for persons wrongfully confined", "description": ""},
        "98": {"title": "Power to compel restoration of abducted females", "description": ""},
        "99": {"title": "Direction, etc., of search-warrants", "description": ""},
        "100": {"title": "Persons in charge of closed place to allow search", "description": ""},
        "101": {"title": "Disposal of things found in search beyond jurisdiction", "description": ""},
        "102": {"title": "Power of police officer to seize certain property", "description": ""},
        "103": {"title": "Magistrate may direct search in his presence", "description": ""},
        "104": {"title": "Power to impound document, etc., produced", "description": ""},
        "105": {"title": "Reciprocal arrangements regarding processes", "description": ""},
        "105A": {"title": "Definitions", "description": ""},
        "105B": {"title": "Assistance in securing transfer of persons", "description": ""},
        "105C": {"title": "Assistance in relation to orders of attachment or forfeiture of property", "description": ""},
        "105D": {"title": "Identifying unlawfully acquired property", "description": ""},
        "105E": {"title": "Seizure or attachment of property", "description": ""},
        "105F": {"title": "Management of properties seized or forfeited", "description": ""},
        "105G": {"title": "Notice of forfeiture of property", "description": ""},
        "105H": {"title": "Forfeiture of property in certain cases", "description": ""},
        "105I": {"title": "Fine in lieu of forfeiture", "description": ""},
        "105J": {"title": "Certain transfers to be null and void", "description": ""},
        "105K": {"title": "Procedure in respect of letter of request", "description": ""},
        "105L": {"title": "Application of this Chapter", "description": ""},
        "106": {"title": "Security for keeping the peace on conviction", "description": ""},
        "107": {"title": "Security for keeping the peace in other cases", "description": ""},
        "108": {"title": "Security for good behaviour from persons disseminating seditious matters", "description": ""},
        "109": {"title": "Security for good behaviour from suspected persons", "description": ""},
        "110": {"title": "Security for good behaviour from habitual offenders", "description": ""},
        "111": {"title": "Order to be made", "description": ""},
        "112": {"title": "Procedure in respect of person present in Court", "description": ""},
        "113": {"title": "Summons or warrant in case of person not so present", "description": ""},
        "114": {"title": "Copy of order to accompany summons or warrant", "description": ""},
        "115": {"title": "Power to dispense with personal attendance", "description": ""},
        "116": {"title": "Inquiry as to truth of information", "description": ""},
        "117": {"title": "Order to give security", "description": ""},
        "118": {"title": "Discharge of person informed against", "description": ""},
        "119": {"title": "Commencement of period for which security is required", "description": ""},
        "120": {"title": "Contents of bond", "description": ""},
        "121": {"title": "Power to reject sureties", "description": ""},
        "122": {"title": "Imprisonment in default of security", "description": ""},
        "123": {"title": "Power to release persons imprisoned for failing to give security", "description": ""},
        "124": {"title": "Security for unexpired period of bond", "description": ""},
        "125": {"title": "Order for maintenance of wives, children and parents", "description": ""},
        "126": {"title": "Procedure", "description": ""},
        "127": {"title": "Alteration in allowance", "description": ""},
        "128": {"title": "Enforcement of order of maintenance", "description": ""},
        "129": {"title": "Dispersal of assembly by use of civil force", "description": ""},
        "130": {"title": "Use of armed forces to disperse assembly", "description": ""},
        "131": {"title": "Power of certain armed force officers to disperse assembly", "description": ""},
        "132": {"title": "Protection against prosecution for acts done under preceding sections", "description": ""},
        "133": {"title": "Conditional order for removal of nuisance", "description": ""},
        "134": {"title": "Service or notification of order", "description": ""},
        "135": {"title": "Person to whom order is addressed to obey or show cause", "description": ""},
        "136": {"title": "Consequences of his failing to do so", "description": ""},
        "137": {"title": "Procedure where existence of public right is denied", "description": ""},
        "138": {"title": "Procedure where he appears to show cause", "description": ""},
        "139": {"title": "Power of Magistrate to direct local investigation and examination of an expert", "description": ""},
        "140": {"title": "Power of Magistrate to furnish written instructions, etc.", "description": ""},
        "141": {"title": "Procedure on order being made absolute and consequences of disobedience", "description": ""},
        "142": {"title": "Injunction pending inquiry", "description": ""},
        "143": {"title": "Magistrate may prohibit repetition or continuance of public nuisance", "description": ""},
        "144": {"title": "Power to issue order in urgent cases of nuisance or apprehended danger", "description": ""},
        "144A": {"title": "Power to prohibit carrying arms in procession or mass drill or mass training with arms", "description": ""},
        "145": {"title": "Procedure where dispute concerning land or water likely to cause breach of peace", "description": ""},
        "146": {"title": "Power to attach subject of dispute and appoint receiver", "description": ""},
        "147": {"title": "Dispute concerning right of use of land or water", "description": ""},
        "148": {"title": "Local inquiry", "description": ""},
        "149": {"title": "Police to prevent cognizable offences", "description": ""},
        "150": {"title": "Information of design to commit cognizable offences", "description": ""},
        "151": {"title": "Arrest to prevent the commission of cognizable offences", "description": ""},
        "152": {"title": "Prevention of injury to public property", "description": ""},
        "153": {"title": "Inspection of weights and measures", "description": ""},
        "154": {"title": "Information in cognizable cases", "description": ""},
        "155": {"title": "Information as to non-cognizable cases and investigation thereof", "description": ""},
        "156": {"title": "Police officer's power to investigate cognizable case", "description": ""},
        "157": {"title": "Procedure for investigation", "description": ""},
        "158": {"title": "Report how submitted", "description": ""},
        "159": {"title": "Power to hold investigation or preliminary inquiry", "description": ""},
        "160": {"title": "Police officer's power to require attendance of witnesses", "description": ""},
        "161": {"title": "Examination of witnesses by police", "description": ""},
        "162": {"title": "Statements to police not to be signed; use in evidence", "description": ""},
        "163": {"title": "No inducement to be offered", "description": ""},
        "164": {"title": "Recording of confessions and statements", "description": ""},
        "164A": {"title": "Medical examination of the victim of rape", "description": ""},
        "165": {"title": "Search by police officer", "description": ""},
        "166": {"title": "When officer in charge may require another to issue search-warrant", "description": ""},
        "166A": {"title": "Letter of request to authority outside India for investigation", "description": ""},
        "166B": {"title": "Letter of request from outside India for investigation in India", "description": ""},
        "167": {"title": "Procedure when investigation cannot be completed in twenty-four hours", "description": ""},
        "168": {"title": "Report of investigation by subordinate police officer", "description": ""},
        "169": {"title": "Release of accused when evidence deficient", "description": ""},
        "170": {"title": "Cases to be sent to Magistrate when evidence sufficient", "description": ""},
        "171": {"title": "Complainant and witnesses not to accompany police officer; no restraint", "description": ""},
        "172": {"title": "Diary of proceedings in investigation", "description": ""},
        "173": {"title": "Report of police officer on completion of investigation", "description": ""},
        "174": {"title": "Police to enquire and report on suicide, etc.", "description": ""},
        "175": {"title": "Power to summon persons", "description": ""},
        "176": {"title": "Inquiry by Magistrate into cause of death", "description": ""},
        "177": {"title": "Ordinary place of inquiry and trial", "description": ""},
        "178": {"title": "Place of inquiry or trial", "description": ""},
        "179": {"title": "Offence triable where act done or consequence ensues", "description": ""},
        "180": {"title": "Place of trial where act relates to other offence", "description": ""},
        "181": {"title": "Place of trial in case of certain offences", "description": ""},
        "182": {"title": "Offences committed by letters, etc.", "description": ""},
        "183": {"title": "Offence committed on journey or voyage", "description": ""},
        "184": {"title": "Place of trial for offences triable together", "description": ""},
        "185": {"title": "Power to order cases tried in different sessions divisions", "description": ""},
        "186": {"title": "High Court to decide district where inquiry or trial shall take place", "description": ""},
        "187": {"title": "Power to issue summons or warrant for offence beyond local jurisdiction", "description": ""},
        "188": {"title": "Offence committed outside India", "description": ""},
        "189": {"title": "Receipt of evidence as to offences committed outside India", "description": ""},
        "190": {"title": "Cognizance of offences by Magistrates", "description": ""},
        "191": {"title": "Transfer on application of the accused", "description": ""},
        "192": {"title": "Making over of cases to Magistrates", "description": ""},
        "193": {"title": "Cognizance of offences by Courts of Session", "description": ""},
        "194": {"title": "Additional and Assistant Sessions Judges to try cases made over by Sessions Judges", "description": ""},
        "195": {"title": "Prosecution for contempt of lawful authority of public servants, for offences against public justice and for offences relating to documents given in evidence", "description": ""},
        "195A": {"title": "Procedure for witnesses in case of threatening, etc.", "description": ""},
        "196": {"title": "Prosecution for offences against the State and for criminal conspiracy to commit such offence", "description": ""},
        "197": {"title": "Prosecution of Judges and public servants", "description": ""},
        "198": {"title": "Prosecution for offences against marriage", "description": ""},
        "198A": {"title": "Prosecution of offences under section 498A of the Indian Penal Code", "description": ""},
        "198B": {"title": "Cognizance of offence", "description": ""},
        "199": {"title": "Prosecution for defamation", "description": ""},
        "200": {"title": "Examination of complainant", "description": ""},
        "201": {"title": "Procedure by Magistrate not competent to take cognizance of the case", "description": ""},
        "202": {"title": "Postponement of issue of process", "description": ""},
        "203": {"title": "Dismissal of complaint", "description": ""},
        "204": {"title": "Issue of process", "description": ""},
        "205": {"title": "Magistrate may dispense with personal attendance of accused", "description": ""},
        "206": {"title": "Special summons in cases of petty offence", "description": ""},
        "207": {"title": "Supply to the accused of copy of police report and other documents", "description": ""},
        "208": {"title": "Supply of copies of statements and documents to accused in other cases triable by Court of Session", "description": ""},
        "209": {"title": "Commitment of case to Court of Session when offence is triable exclusively by it", "description": ""}
    }


if __name__ == "__main__":
    # Test the function
    crpc_db = create_complete_crpc_database()
    print(f"Created CrPC database with {len(crpc_db)} sections")
    # Print first 5 sections as example
    for i, (section_num, section_data) in enumerate(list(crpc_db.items())[:5]):
        print(f"{section_num}: {section_data['title']}")