services:
  - type: web
    name: law-agent-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.15
      - key: WEB_CONCURRENCY
        value: 4